/**
 * dopamine toolchain — the AGGREGATE root SwiftPM package emitter.
 *
 * SwiftPM has no mainstream package registry: a consumer depends on a package by
 * GIT URL + a semver tag, and a git URL always resolves the Package.swift at the
 * REPO ROOT. So to make the effects installable we publish ONE aggregate package
 * at the repo root that exposes `DopamineCore` + every `DopamineEffect<Name>` as
 * library products:
 *
 *   .package(url: "https://github.com/10in30/dopamine.git", from: "0.1.0")
 *   // then pick products: "DopamineCore", "DopamineEffectComic", …
 *
 * Its targets reuse the SAME sources the per-effect `dist/swift/` packages carry:
 * the in-repo `swift/Sources/DopamineCore` runtime + each generated
 * `dist/swift/DopamineEffect<Name>/Sources/...` tree. The standalone per-effect
 * packages stay (the iOS/macOS demo consumes them by path); this aggregate is the
 * URL-installable face of the same generated bytes. It is NOT committed to `main`
 * (its effect target paths live under the gitignored `dist/`) — the release
 * workflow runs `dopamine build`, writes this manifest, and commits both onto the
 * tagged release tree only (see `.github/workflows/swift-release.yml`).
 */

const HEADER = `// swift-tools-version:5.9
// @generated by @dopaminefx/build — do not edit.
// The AGGREGATE Dopamine SwiftPM package: DopamineCore + every effect as a
// library product, installable by git URL + semver tag. Generated by
// scripts/swift-aggregate.mjs onto the release tag (never committed to main).`;

/**
 * Emit the aggregate root `Package.swift`.
 * @param {Array<{ module: string, slug: string, hasFonts: boolean }>} entries —
 *        one per effect, expected pre-sorted by module for stable output.
 * @param {{ platforms?: string[] }} [opts] — SwiftPM platform clauses (without the
 *        leading dot), e.g. `["iOS(.v15)", "macOS(.v12)"]`.
 */
export function emitAggregateSwiftPackage(entries, { platforms = ["iOS(.v15)", "macOS(.v12)"] } = {}) {
  const plats = platforms.map((p) => `.${p}`).join(", ");

  const products = entries
    .map((e) => `        .library(name: "${e.module}", targets: ["${e.module}"]),`)
    .join("\n");

  const targets = entries
    .map((e) => {
      // The generated dist tree is identical to the standalone package's, so the
      // resource clauses mirror swift.mjs's `emitPackageSwift` (dope + optional
      // bundled faces + the Metal shaders).
      const fontsRes = e.hasFonts ? `\n                .copy("Resources/fonts"),` : "";
      return `        .target(
            name: "${e.module}",
            dependencies: ["DopamineCore"],
            path: "dist/swift/${e.module}/Sources/${e.module}",
            resources: [
                .copy("Resources/${e.slug}.dope.json"),${fontsRes}
                .process("Shaders"),
            ]
        ),`;
    })
    .join("\n");

  return `${HEADER}
import PackageDescription

let package = Package(
    name: "Dopamine",
    platforms: [${plats}],
    products: [
        .library(name: "DopamineCore", targets: ["DopamineCore"]),
${products}
    ],
    targets: [
        .target(name: "DopamineCore", path: "swift/Sources/DopamineCore"),
${targets}
    ]
)
`;
}
