/**
 * dopamine toolchain — Android (Gradle library) package emitter.
 *
 * Turns a single effect folder into a STANDALONE Android library module under
 * `dist/android/dopamine-effect-<slug>/`:
 *
 *   dist/android/dopamine-effect-comic/
 *     build.gradle.kts                       (generated; deps dopamine-gl)
 *     src/main/AndroidManifest.xml           (generated)
 *     src/main/kotlin/<pkg path>/*.kt        (the hand-written sources, copied)
 *     src/main/assets/<slug>.dope.json       (the PORTABLE embedded data spine)
 *
 * Depends on `dopamine-gl` (the GL backbone) — a local Gradle project in this
 * monorepo (settings includes the module from dist); an external author points it
 * at a published Maven artifact. The build.gradle.kts content matches the
 * known-good per-effect module so a relocated build compiles identically.
 */

import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { generateAndroidShaderKt } from "./android-shader.mjs";
import { assertFactoryGeneratable, buildFrameArraysSpec, emitKotlinFactory } from "./factory.mjs";

function emitBuildGradle({ namespace, slug }) {
  return `// @generated by @dopamine/build from effects/${slug}/android — do not edit.
// Standalone Android library for the effect: its GLSL shader, bespoke tempo, panel
// draw, factory + the byte-identical .dope (assets/), depending on dopamine-gl +
// dopamine-core. In this monorepo dopamine-gl is the local Gradle project; an
// external author would depend on a published artifact.

plugins {
    id("com.android.library")
    kotlin("android")
}

android {
    namespace = "${namespace}"
    compileSdk = 35
    defaultConfig { minSdk = 24 }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

dependencies {
    api(project(":dopamine-gl"))
}
`;
}

const MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" />
`;

/**
 * Generate the Android library artifacts for one loaded effect.
 * @returns {Promise<Array<{ path: string, content: string }>>} dist-relative paths.
 */
export async function generateAndroidLibrary({ root, eff, fonts = [], logic = null }) {
  const { dir, doc, slug, dope } = eff;
  const a = doc["x-build"].android ?? {};
  const module = a.module ?? `dopamine-effect-${slug}`;
  const namespace = a.namespace ?? `ai.dopamine.effect.${slug}`;
  const srcAbs = join(dir, a.sources ?? "android");
  const pkgPath = namespace.replace(/\./g, "/");

  const modRel = join("android", module);
  const out = [];

  // (1) Kotlin sources (tempo, panel, factory) copied under the package path. When
  //     the effect declares a single-source shader (`x-build.shader`), its
  //     `<Name>Shader.kt` is GENERATED from the web GLSL (the same source the MSL is
  //     transpiled from) instead of being hand-written — so the shader can't drift.
  //     A FULLY DECLARATIVE effect ships NO android/ dir at all and gets its
  //     registration shim GENERATED from the `.dope` too (factory.mjs). When the
  //     effect declares generated per-frame-geometry logic (`x-build.logic`), its
  //     `<Name>Renderer.kt` is TRANSPILED from the single web TS source
  //     (logic.mjs) — never hand-shipped.
  const shaderCfg = doc["x-build"].shader;
  const Name = slug.charAt(0).toUpperCase() + slug.slice(1);
  const generatedShaderFile = shaderCfg ? `${Name}Shader.kt` : null;
  const generatedRendererFile = logic ? `${Name}Renderer.kt` : null;
  let handNames = [];
  try { handNames = (await readdir(srcAbs)).sort(); } catch { /* no android/ dir */ }
  const hand = handNames.filter(
    (n) => n.endsWith(".kt") && n !== generatedShaderFile && n !== generatedRendererFile,
  );
  for (const name of hand) {
    out.push({ path: join(modRel, "src/main/kotlin", pkgPath, name), content: await readFile(join(srcAbs, name), "utf8") });
  }
  // No hand-written factory (`<Name>.kt`) ⇒ generate the registration shim: a
  // FULLY DECLARATIVE effect ships NO android/ dir at all, and a PANEL effect
  // (`render.panel`) ships ONLY its `<Name>Panel.kt` draw — the panel-draw seam
  // the generated factory wires (`draw<Name>Panel`).
  if (!hand.includes(`${Name}.kt`)) {
    assertFactoryGeneratable(doc, slug, "android");
    const panel = !!doc.render?.panel;
    if (panel && !hand.includes(`${Name}Panel.kt`)) {
      throw new Error(
        `dopamine: effects/${slug} declares render.panel but has no android/${Name}Panel.kt — ` +
          `the generated factory wires the hand-written draw${Name}Panel (the panel-draw seam).`,
      );
    }
    out.push({
      path: join(modRel, "src/main/kotlin", pkgPath, `${Name}.kt`),
      content: emitKotlinFactory(slug, namespace, buildFrameArraysSpec(doc, slug, logic), panel),
    });
  }
  if (shaderCfg) {
    const gen = await generateAndroidShaderKt({ root, dir, slug, namespace, shaderCfg });
    out.push({ path: join(modRel, "src/main/kotlin", pkgPath, gen.name), content: gen.content });
  }
  if (logic) {
    out.push({ path: join(modRel, "src/main/kotlin", pkgPath, `${Name}Renderer.kt`), content: logic.kotlin });
  }

  // (2) the PORTABLE .dope asset (byte-identical to the swift/web embeds).
  out.push({ path: join(modRel, "src/main/assets", `${slug}.dope.json`), content: dope });

  // (2b) the bundled display faces (ttf, converted from the shared woff2) — the
  //      panel loads these via Typeface.createFromAsset("fonts/<name>.ttf").
  for (const f of fonts) {
    out.push({ path: join(modRel, "src/main/assets", "fonts", f.name), content: f.content });
  }

  // (3) generated manifest + build.gradle.kts.
  out.push({ path: join(modRel, "src/main/AndroidManifest.xml"), content: MANIFEST });
  out.push({ path: join(modRel, "build.gradle.kts"), content: emitBuildGradle({ namespace, slug }) });

  return out;
}
