/**
 * Generate an effect's Android shader `<Name>Shader.kt` from the canonical web
 * GLSL — the same single source the MSL is transpiled from. Android OpenGL ES 3.0
 * speaks GLSL ES 3.00, the SAME dialect as WebGL2, so the body is reused verbatim;
 * the only platform changes (cf. the hand-ports this replaces) are:
 *   • the `${GLSL_*}` look-chunk interpolations are KEPT (Kotlin uses the same
 *     `${…}` syntax) so the look stays in `dopamine-core/Look.kt` ONCE; `${GLSL_LIGHT_OUT}`
 *     is appended to the chunk block,
 *   • non-chunk JS interpolations (e.g. `${MAX_CURTAINS}`) are resolved to their value,
 *   • the final emit `fragColor = vec4(max(col,0.0),1.0)` → `fragColor = dopLightOut(col)`
 *     (premultiplied light-out for the self-contained overlay).
 *
 * Output is gated TOKEN-EQUIVALENT (comments/whitespace ignored) against the
 * committed hand-port snapshot in tools/dopamine/test, and pixel-gated by the golden
 * frame (which renders exactly this web→android derivation).
 */
import { loadWebShaderSource, extractTemplate } from "./glsl-load.mjs";

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * Transform a raw web template body → an Android Kotlin raw-string body:
 *  - resolve non-`GLSL_*` `${X}` interpolations to the module's exported value,
 *  - collect the `GLSL_*` chunk names referenced (kept as `${…}`).
 */
function transformBody(body, mod, chunks) {
  return body.replace(/\$\{([A-Za-z_]\w*)\}/g, (_m, id) => {
    if (id.startsWith("GLSL_")) { chunks.add(id); return `\${${id}}`; }
    if (mod[id] !== undefined) return String(mod[id]);
    throw new Error(`android-shader: cannot resolve \${${id}}`);
  });
}

/**
 * @returns {{ name: string, content: string }} the generated `<Name>Shader.kt`.
 */
export async function generateAndroidShaderKt({ root, dir, slug, namespace, shaderCfg }) {
  const Name = pascal(slug);
  // The Android factory imports `<SLUG_UPPER>_{VERTEX,FRAGMENT}_SRC` (e.g. inkstroke →
  // INKSTROKE_*, even though the web abbreviates it INK_*). Extract from the web by
  // its own export names; EMIT under the slug-derived Android names the factory expects.
  const UPPER = slug.toUpperCase();
  const vertexName = `${UPPER}_VERTEX_SRC`;
  const fragmentName = `${UPPER}_FRAGMENT_SRC`;
  const { srcText, mod } = await loadWebShaderSource(root, dir, shaderCfg);
  const chunks = new Set();

  const vertexBody = transformBody(extractTemplate(srcText, shaderCfg.vertexExport), mod, chunks);
  let fragmentBody = transformBody(extractTemplate(srcText, shaderCfg.fragmentExport), mod, chunks);

  // Append the light-out chunk after the leading chunk block (i.e. right after the
  // last `${GLSL_*}` interpolation), then swap the web emit for the premultiplied one.
  fragmentBody = fragmentBody.replace(/(\$\{GLSL_\w+\})(?![\s\S]*\$\{GLSL_\w+\})/, "$1\n${GLSL_LIGHT_OUT}");
  fragmentBody = fragmentBody.replace(
    "fragColor = vec4(max(col, 0.0), 1.0);",
    "fragColor = dopLightOut(col);",
  );
  chunks.add("GLSL_LIGHT_OUT");

  const imports = [...chunks].sort().map((c) => `import ai.dopamine.core.${c}`).join("\n");
  const content = `// @generated by @dopamine/build from the web GLSL (effects/${slug}/${shaderCfg.web}).
// Android OpenGL ES 3.0 == GLSL ES 3.00 (the WebGL2 dialect), so the shader body is
// the web source verbatim; the look chunks come from dopamine-core/Look.kt ONCE (the
// \${GLSL_*} refs below), and the only emit change is dopLightOut (premultiplied light).
// DO NOT EDIT — regenerate via \`node tools/dopamine/src/cli.mjs build\`.
package ${namespace}

${imports}

val ${vertexName}: String = """${vertexBody}"""

val ${fragmentName}: String = """${fragmentBody}"""
`;
  return { name: `${Name}Shader.kt`, content };
}
