/**
 * dopamine toolchain — Android (Gradle library) package emitter.
 *
 * Turns a single effect folder into a STANDALONE Android library module under
 * `dist/android/dopamine-effect-<slug>/`:
 *
 *   dist/android/dopamine-effect-comic/
 *     build.gradle.kts                       (generated; deps dopamine-gl)
 *     src/main/AndroidManifest.xml           (generated)
 *     src/main/kotlin/<pkg path>/*.kt        (the hand-written sources, copied)
 *     src/main/assets/<slug>.dope.json       (the PORTABLE embedded data spine)
 *
 * Depends on `dopamine-gl` (the GL backbone) — a local Gradle project in this
 * monorepo (settings includes the module from dist); an external author points it
 * at a published Maven artifact. The build.gradle.kts content matches the
 * known-good per-effect module so a relocated build compiles identically.
 */

import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";

function emitBuildGradle({ namespace, slug }) {
  return `// @generated by @dopamine/build from effects/${slug}/android — do not edit.
// Standalone Android library for the effect: its GLSL shader, bespoke tempo, panel
// draw, factory + the byte-identical .dope (assets/), depending on dopamine-gl +
// dopamine-core. In this monorepo dopamine-gl is the local Gradle project; an
// external author would depend on a published artifact.

plugins {
    id("com.android.library")
    kotlin("android")
}

android {
    namespace = "${namespace}"
    compileSdk = 35
    defaultConfig { minSdk = 24 }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

dependencies {
    api(project(":dopamine-gl"))
}
`;
}

const MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" />
`;

/**
 * Generate the Android library artifacts for one loaded effect.
 * @returns {Promise<Array<{ path: string, content: string }>>} dist-relative paths.
 */
export async function generateAndroidLibrary({ eff, fonts = [] }) {
  const { dir, doc, slug, dope } = eff;
  const a = doc["x-build"].android ?? {};
  const module = a.module ?? `dopamine-effect-${slug}`;
  const namespace = a.namespace ?? `ai.dopamine.effect.${slug}`;
  const srcAbs = join(dir, a.sources ?? "android");
  const pkgPath = namespace.replace(/\./g, "/");

  const modRel = join("android", module);
  const out = [];

  // (1) hand-written Kotlin sources (shader string, tempo, panel, factory) under
  //     the package path.
  for (const name of (await readdir(srcAbs)).sort()) {
    if (name.endsWith(".kt")) {
      out.push({ path: join(modRel, "src/main/kotlin", pkgPath, name), content: await readFile(join(srcAbs, name), "utf8") });
    }
  }

  // (2) the PORTABLE .dope asset (byte-identical to the swift/web embeds).
  out.push({ path: join(modRel, "src/main/assets", `${slug}.dope.json`), content: dope });

  // (2b) the bundled display faces (ttf, converted from the shared woff2) — the
  //      panel loads these via Typeface.createFromAsset("fonts/<name>.ttf").
  for (const f of fonts) {
    out.push({ path: join(modRel, "src/main/assets", "fonts", f.name), content: f.content });
  }

  // (3) generated manifest + build.gradle.kts.
  out.push({ path: join(modRel, "src/main/AndroidManifest.xml"), content: MANIFEST });
  out.push({ path: join(modRel, "build.gradle.kts"), content: emitBuildGradle({ namespace, slug }) });

  return out;
}
