/**
 * dopamine toolchain — generated platform FACTORY SHELLS.
 *
 * For a fully declarative effect, the per-platform "factory" is pure
 * boilerplate: load the bundled `.dope`, resolve through the shared loader,
 * and wire the generic dope pass config to the generated shader + uniforms
 * glue. Every token is derivable from the `.dope`, so an effect that ships a
 * single-source shader (`x-build.shader`) need not ship ANY `swift/` or
 * `android/` sources — the Swift factory shell (+ its resource-bundle
 * accessor) and the Kotlin registration shim are emitted here, the same
 * posture as the generated `<Name>Uniforms` glue and the transpiled shaders.
 *
 * The templates are seeded from — and byte-equivalent (modulo the header) to —
 * the historical hand-written shims of the datafied effects, which all
 * converged on this exact shape; the per-effect golden test pins the output.
 * Effects with genuinely code-shaped factory bits (the panel hybrids, CPU
 * frame-geometry precomputes) keep hand-written sources — a fully supported
 * path.
 */

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * Guard: a generated factory shell only works for a FULLY DECLARATIVE effect
 * (the generic dope pass config needs the datafied sections). Throws with a
 * pointer at the alternatives otherwise.
 */
export function assertFactoryGeneratable(doc, slug, platform) {
  const missing = [];
  if (!doc["x-build"]?.shader?.web || !doc["x-build"].shader.generateMSL) {
    missing.push("x-build.shader (single-source, generateMSL)");
  }
  if (!doc.tempo?.frame) missing.push("tempo.frame");
  if (doc.render?.shadowHeightFrac === undefined) missing.push("render.shadowHeightFrac");
  if (!doc.binding?.scatterKey) missing.push("binding.scatterKey");
  if (missing.length) {
    throw new Error(
      `dopamine: effects/${slug} has no ${platform} sources, and a factory shell can only be ` +
        `generated for a fully declarative effect (missing: ${missing.join(", ")}). ` +
        `Either datafy the effect or add hand-written ${platform} sources.`,
    );
  }
}

const genHeader = (slug) =>
  `// @generated by @dopamine/build from effects/${slug}/${slug}.dope.json — do not edit.`;

/**
 * The Swift factory shell (`<Name>.swift`): the portable `EffectFactory` class
 * + the Metal-only `passConfig()` over the generated packer. Public API matches
 * the historical hand shims (`<Name>()`, `<Name>.passConfig()`).
 */
export function emitSwiftFactory(slug) {
  const Name = pascal(slug);
  return `${genHeader(slug)}
//
// ${Name} as a Dopamine effect on the Swift backbone — the DATA-DRIVEN factory
// shell. This effect ships NO hand-written Swift: everything that isn't the
// shader lives in ${slug}.dope.json — the mood→params mapping + OKLCH palette
// (the loader), the per-frame logic (\`tempo.frame\`), \`render.shadowHeightFrac\`,
// \`render.consts\`, \`render.config\`, any \`tempo.loop\` contract and the uniform
// \`binding\` contract. The generic \`DopePassConfig\` interprets that data through
// the shared Metal pass runner. (The MSL is transpiled from the canonical web
// GLSL by the toolchain; \`${Name}Uniforms\` + \`pack${Name}Uniforms\` are generated
// from the \`.dope\` binding contract.)

import Foundation
import DopamineCore

/// ${Name}: resolves a feeling → the flat \`.dope\` param bag. The drawable side
/// is Metal-only (below).
public final class ${Name}: EffectFactory {
    public let name = "${slug}"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled \`.dope\` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("${slug}.dope", bundle: .module)
    }

    /// Resolve via the shared loader. The clamp consts and the scatter key come
    /// from the \`.dope\` itself (\`render.consts\` / \`binding.scatterKey\`) —
    /// byte-identical to the web.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling)
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)
public extension ${Name} {
    /// The DATA-DRIVEN pass config: \`tempo.frame\`, \`render.shadowHeightFrac\`
    /// and \`render.config\` all come from the bundled \`.dope\`, evaluated by the
    /// shared backbone.
    static func passConfig() throws -> DopePassConfig<${Name}Uniforms> {
        try DopePassConfig(
            doc: DopeResource.loadDope("${slug}.dope", bundle: .module),
            vertexFunction: "${slug}_vertex",
            fragmentFunction: "${slug}_fragment",
            packUniforms: pack${Name}Uniforms
        )
    }
}
#endif
`;
}

/**
 * The Swift resource-bundle accessor (`<Name>Bundle.swift`): hands the
 * package's compiled `default.metallib` to an app target.
 */
export function emitSwiftBundle(slug) {
  const Name = pascal(slug);
  return `${genHeader(slug)}
//
// Exposes the effect's resource bundle so an APP target (the iOS demo) can load
// the compiled \`default.metallib\` SwiftPM built from this package's \`Shaders/\`.
//
// \`Bundle.module\` is internal to the package that declares the resources, so an
// app linking the effect package cannot reach the metallib directly. This tiny
// public accessor hands it over. Metal-only: the metallib only exists on an
// Apple toolchain build, and on Linux there is no Metal to load it with.

#if canImport(Metal)
import Foundation

public enum ${Name}Resources {
    /// The effect package's resource bundle (contains the compiled
    /// \`default.metallib\` + the bundled \`.dope\`). Use with
    /// \`device.makeDefaultLibrary(bundle: ${Name}Resources.bundle)\`.
    public static var bundle: Bundle { .module }
}
#endif
`;
}

/**
 * The Kotlin registration shim (`<Name>.kt`). Public API matches the
 * historical hand shims (`<Name>(context)`, `<Name>.register(context)`).
 */
export function emitKotlinFactory(slug, namespace) {
  const Name = pascal(slug);
  const SLUG = slug.toUpperCase();
  return `${genHeader(slug)}
//
// ${Name} as a Dopamine effect on the Android backbone — the DATA-DRIVEN
// registration shim. This effect ships NO hand-written Kotlin: everything that
// isn't the GLSL lives in ${slug}.dope.json — the mood→params mapping + palette
// (the loader), the per-frame logic (\`tempo.frame\`), \`render.shadowHeightFrac\`,
// \`render.consts\`, \`render.config\`, \`tempo.reducedMotion\`, any \`tempo.loop\`
// contract and the uniform \`binding\` contract. \`dopePassPlan\` + \`dopePassConfig\`
// interpret that data through the generic pass runner. (The shader Kotlin is
// toolchain-generated from the same canonical web GLSL as the MSL.) The \`.dope\`
// bytes are the SAME as the web's (byte-parity proven by the 192-case grid).

package ${namespace}

import ai.dopamine.core.DopeDoc
import ai.dopamine.core.DopeException
import ai.dopamine.core.DopePassPlan
import ai.dopamine.core.DopeResolveInput
import ai.dopamine.core.DopeValue
import ai.dopamine.core.EffectRegistry
import ai.dopamine.core.dopePassPlan
import ai.dopamine.core.parseDope
import ai.dopamine.core.resolveDopeParams
import ai.dopamine.gl.DrawableEffect
import ai.dopamine.gl.EffectContext
import ai.dopamine.gl.EffectInstance
import ai.dopamine.gl.PassConfig
import ai.dopamine.gl.createPassInstance
import ai.dopamine.gl.dopePassConfig
import android.content.Context

class ${Name}(context: Context) : DrawableEffect {
    override val name: String = "${slug}"

    // Load the bundled \`.dope\` (the EXACT web bytes) from the merged APK assets —
    // proving the data spine is shared verbatim across platforms.
    val doc: DopeDoc = parseDope(
        context.assets.open("${slug}.dope.json").bufferedReader(Charsets.UTF_8).use { it.readText() },
    )

    // The whole factory (resolve consts/scatter, uniforms/bindings, the
    // per-frame logic, shadow height, reduced motion, the loop contract) is
    // data: ${slug}.dope.json interpreted by the core backbone.
    private val plan: DopePassPlan = dopePassPlan(doc)
    private val scatterKey: String =
        plan.scatterKey ?: throw DopeException("dope: \${doc.id} has no binding.scatterKey")
    private val config: PassConfig = dopePassConfig(doc, ${SLUG}_VERTEX_SRC, ${SLUG}_FRAGMENT_SRC, plan)

    override fun resolve(feeling: DopeResolveInput): Map<String, DopeValue> =
        resolveDopeParams(doc, feeling, consts = plan.consts, scatterKey = scatterKey)

    override fun create(params: Map<String, DopeValue>, ctx: EffectContext): EffectInstance =
        createPassInstance(config, params, ctx)

    override val reducedMotionPeakMs: Double? = plan.reducedMotionPeakMs
    override val reducedMotionHoldMs: Double? = plan.reducedMotionHoldMs

    // The CONTINUOUS-loop contract (\`tempo.loop\`), null for one-shots: the
    // conductor re-arms a looping effect until the host stops the play handle.
    override val loop = doc.loop

    companion object {
        /** Construct + register the effect (needs a Context for the \`.dope\` asset). */
        fun register(context: Context): ${Name} {
            val fx = ${Name}(context.applicationContext)
            EffectRegistry.register(fx)
            return fx
        }
    }
}
`;
}
