/**
 * dopamine toolchain — generated platform FACTORY SHELLS.
 *
 * For a fully declarative effect, the per-platform "factory" is pure
 * boilerplate: load the bundled `.dope`, resolve through the shared loader,
 * and wire the generic dope pass config to the generated shader + uniforms
 * glue. Every token is derivable from the `.dope`, so an effect that ships a
 * single-source shader (`x-build.shader`) need not ship ANY `swift/` or
 * `android/` sources — the Swift factory shell (+ its resource-bundle
 * accessor) and the Kotlin registration shim are emitted here, the same
 * posture as the generated `<Name>Uniforms` glue and the transpiled shaders.
 *
 * The templates are seeded from — and byte-equivalent (modulo the header) to —
 * the historical hand-written shims of the datafied effects, which all
 * converged on this exact shape; the per-effect golden test pins the output.
 * Effects with genuinely code-shaped factory bits (the panel hybrids, CPU
 * frame-geometry precomputes) keep hand-written sources — a fully supported
 * path.
 */

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * Logic entry params with a RESERVED meaning: the runner-supplied frame
 * geometry + clocks. Everything else is looked up in the resolved param bag by
 * name. (The names are the web `frameArrays` hook's vocabulary — the single
 * logic source is authored against it.)
 */
const RESERVED_LOGIC_ARGS = {
  swift: {
    width: "width: Double(width)",
    height: "height: Double(height)",
    originX: "originX: Double(origin.x)",
    originY: "originY: Double(origin.y)",
    elapsedMs: "elapsedMs: info.animMs",
    life: "life: info.life",
  },
  kotlin: {
    width: "width = geom.widthPx.toDouble()",
    height: "height = geom.heightPx.toDouble()",
    originX: "originX = geom.originX.toDouble()",
    originY: "originY = geom.originY.toDouble()",
    elapsedMs: "elapsedMs = info.animMs",
    life: "life = info.life",
  },
};

/**
 * Derive the generated factories' `frameArrays` wiring for an effect with
 * generated per-frame-geometry logic (`x-build.logic`): the transpiled entry
 * function is called each frame and its returned bundle fields are bound
 * through the `.dope` `binding.arrays` contract (web/GL: named uniform arrays;
 * Metal: `PassFrameArray(bufferIndex:)` fragment buffers). Returns null when
 * the effect has no logic; throws when logic and the binding contract disagree.
 */
export function buildFrameArraysSpec(doc, slug, logic) {
  if (!logic) return null;
  const arrays = doc.binding?.arrays ?? [];
  if (!arrays.length) {
    throw new Error(
      `dopamine: effects/${slug} has x-build.logic but no binding.arrays — the generated ` +
        `factories need the arrays contract to wire the renderer into the frameArrays seam.`,
    );
  }
  const entry = logic.model.entry;
  const bundleFields = logic.model.interfaces[entry.returnType.slice(7)].fields;
  for (const a of arrays) {
    if (!bundleFields.includes(a.name)) {
      throw new Error(`dopamine: effects/${slug} binding.arrays "${a.name}" is not a field of the logic bundle (${bundleFields.join(", ")})`);
    }
    if (![2, 3, 4].includes(a.size)) throw new Error(`dopamine: effects/${slug} binding.arrays "${a.name}" needs size 2|3|4`);
    if (!(a.buffer >= 1)) throw new Error(`dopamine: effects/${slug} binding.arrays "${a.name}" needs a Metal buffer index >= 1`);
  }
  return { entryName: entry.name, params: entry.params.map((p) => p.name), arrays };
}

/**
 * Guard: a generated factory shell only works for a FULLY DECLARATIVE effect
 * (the generic dope pass config needs the datafied sections). Throws with a
 * pointer at the alternatives otherwise.
 */
export function assertFactoryGeneratable(doc, slug, platform) {
  const missing = [];
  if (!doc["x-build"]?.shader?.web || !doc["x-build"].shader.generateMSL) {
    missing.push("x-build.shader (single-source, generateMSL)");
  }
  if (!doc.tempo?.frame) missing.push("tempo.frame");
  if (doc.render?.shadowHeightFrac === undefined) missing.push("render.shadowHeightFrac");
  if (!doc.binding?.scatterKey) missing.push("binding.scatterKey");
  if (missing.length) {
    throw new Error(
      `dopamine: effects/${slug} has no ${platform} sources, and a factory shell can only be ` +
        `generated for a fully declarative effect (missing: ${missing.join(", ")}). ` +
        `Either datafy the effect or add hand-written ${platform} sources.`,
    );
  }
}

const genHeader = (slug) =>
  `// @generated by @dopaminefx/build from effects/${slug}/${slug}.dope.json — do not edit.`;

/**
 * The Swift factory shell (`<Name>.swift`): the portable `EffectFactory` class
 * + the Metal-only `passConfig()` over the generated packer. Public API matches
 * the historical hand shims (`<Name>()`, `<Name>.passConfig()`). When the
 * effect has generated per-frame-geometry logic, `frameArrays` (the
 * `buildFrameArraysSpec` wiring) emits the closure that calls the generated
 * renderer and binds its bundle through `binding.arrays`.
 */
export function emitSwiftFactory(slug, frameArrays = null, panelMode = "none") {
  const Name = pascal(slug);
  // panelMode: "none" (pure pass), "panel" (panel-kind whole-content panel at
  // texture(0) — the DopePanelPassConfig runner), or "sprite" (a PASS hybrid
  // with a sprite panel at an arbitrary unit + optional baked-SDF aux — the
  // DopeSpritePanelPassConfig runner: solarbloom's motes panel + ✓ SDF).
  const hasPanel = panelMode === "panel" || panelMode === "sprite";
  const ConfigName = panelMode === "panel"
    ? "DopePanelPassConfig"
    : panelMode === "sprite"
      ? "DopeSpritePanelPassConfig"
      : "DopePassConfig";
  let frameArraysArg = "";
  if (frameArrays) {
    const { entryName, params, arrays } = frameArrays;
    const reserved = RESERVED_LOGIC_ARGS.swift;
    const needsNum = params.some((p) => !reserved[p]);
    const args = params
      .map((p) => reserved[p] ?? `${p}: num("${p}")`)
      .map((a, i, all) => `                    ${a}${i < all.length - 1 ? "," : ""}`)
      .join("\n");
    const buffers = arrays
      .map((a, i) => `                    PassFrameArray(bufferIndex: ${a.buffer}, data: out.${a.name})${i < arrays.length - 1 ? "," : ""}`)
      .join("\n");
    frameArraysArg = `,
            frameArrays: { info, params, width, height, origin in
                // The generated ${Name}Renderer (transpiled from the single web
                // logic module) precomputes the frame geometry; \`binding.arrays\`
                // maps its bundle onto the fragment buffers.
${needsNum ? `                func num(_ k: String) -> Double { if case let .number(v)? = params[k] { return v }; return 0 }\n` : ""}                let out = ${entryName}(
${args}
                )
                return [
${buffers}
                ]
            }`;
  }
  const configType = `${ConfigName}<${Name}Uniforms>`;
  const panelArg = hasPanel
    ? `,
            // The hand-written per-effect panel draw (the panel-draw seam:
            // effects/${slug}/swift/${Name}Panel.swift) — the ONLY per-effect
            // Swift; the backbone redraws + uploads it every frame.
            drawPanel: draw${Name}Panel`
    : "";
  const panelNote = panelMode === "sprite"
    ? `// shell. The ONLY hand-written Swift is the Core Graphics SPRITE-PANEL draw
// (${Name}Panel.swift — a PASS hybrid: the panel binds at its render.panel unit
// ALONGSIDE the baked-SDF aux; panel geometry is code by design); everything else`
    : panelMode === "panel"
      ? `// shell. The ONLY hand-written Swift is the Core Graphics panel draw
// (${Name}Panel.swift — panel geometry is code by design); everything that isn't the`
      : `// shell. This effect ships NO hand-written Swift: everything that isn't the`;
  return `${genHeader(slug)}
//
// ${Name} as a Dopamine effect on the Swift backbone — the DATA-DRIVEN factory
${panelNote}
// shader lives in ${slug}.dope.json — the mood→params mapping + OKLCH palette
// (the loader), the per-frame logic (\`tempo.frame\`), \`render.shadowHeightFrac\`,
// \`render.consts\`, \`render.config\`, any \`tempo.loop\` contract and the uniform
// \`binding\` contract. The generic \`${ConfigName}\` interprets that data through
// the shared Metal pass runner. (The MSL is transpiled from the canonical web
// GLSL by the toolchain; \`${Name}Uniforms\` + \`pack${Name}Uniforms\` are generated
// from the \`.dope\` binding contract.)

import Foundation
import DopamineCore

/// ${Name}: resolves a feeling → the flat \`.dope\` param bag. The drawable side
/// is Metal-only (below).
public final class ${Name}: EffectFactory {
    public let name = "${slug}"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled \`.dope\` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("${slug}.dope", bundle: .module)
    }

    /// Resolve via the shared loader. The clamp consts and the scatter key come
    /// from the \`.dope\` itself (\`render.consts\` / \`binding.scatterKey\`) —
    /// byte-identical to the web.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling)
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

${hasPanel ? "#if canImport(Metal) && canImport(QuartzCore)" : "#if canImport(Metal)"}
public extension ${Name} {
    /// The DATA-DRIVEN pass config: \`tempo.frame\`, \`render.shadowHeightFrac\`
    /// and \`render.config\` all come from the bundled \`.dope\`, evaluated by the
    /// shared backbone.
    static func passConfig() throws -> ${configType} {
        try ${ConfigName}(
            doc: DopeResource.loadDope("${slug}.dope", bundle: .module),
            vertexFunction: "${slug}_vertex",
            fragmentFunction: "${slug}_fragment",
            packUniforms: pack${Name}Uniforms${frameArraysArg}${panelArg}
        )
    }
}
#endif
`;
}

/**
 * The Swift resource-bundle accessor (`<Name>Bundle.swift`): hands the
 * package's compiled `default.metallib` to an app target.
 */
export function emitSwiftBundle(slug) {
  const Name = pascal(slug);
  return `${genHeader(slug)}
//
// Exposes the effect's resource bundle so an APP target (the iOS demo) can load
// the compiled \`default.metallib\` SwiftPM built from this package's \`Shaders/\`.
//
// \`Bundle.module\` is internal to the package that declares the resources, so an
// app linking the effect package cannot reach the metallib directly. This tiny
// public accessor hands it over. Metal-only: the metallib only exists on an
// Apple toolchain build, and on Linux there is no Metal to load it with.

#if canImport(Metal)
import Foundation

public enum ${Name}Resources {
    /// The effect package's resource bundle (contains the compiled
    /// \`default.metallib\` + the bundled \`.dope\`). Use with
    /// \`device.makeDefaultLibrary(bundle: ${Name}Resources.bundle)\`.
    public static var bundle: Bundle { .module }
}
#endif
`;
}

/**
 * The Kotlin registration shim (`<Name>.kt`). Public API matches the
 * historical hand shims (`<Name>(context)`, `<Name>.register(context)`). When
 * the effect has generated per-frame-geometry logic, `frameArrays` (the
 * `buildFrameArraysSpec` wiring) emits the lambda that calls the generated
 * renderer and binds its bundle through `binding.arrays` (by NAME — GL sets
 * uniform arrays like the web does).
 */
export function emitKotlinFactory(slug, namespace, frameArrays = null, panelMode = "none") {
  const Name = pascal(slug);
  const SLUG = slug.toUpperCase();
  // panelMode: "none" (pure pass), "panel" (panel-kind whole-content panel via
  // the Canvas panel runner — dopePanelConfig/createPanelInstance), or "sprite"
  // (a PASS hybrid with a sprite panel at an arbitrary unit + baked-SDF aux —
  // the PASS runner's panel seam: dopePassConfig(..., draw=) / createPassInstance).
  const isPanelKind = panelMode === "panel";
  const isSprite = panelMode === "sprite";
  let configDecl = `private val config: PassConfig = dopePassConfig(doc, ${SLUG}_VERTEX_SRC, ${SLUG}_FRAGMENT_SRC, plan)`;
  if (isPanelKind) {
    configDecl = `private val config: PanelConfig = dopePanelConfig(
        doc, ${SLUG}_VERTEX_SRC, ${SLUG}_FRAGMENT_SRC, plan,
        // The hand-written per-effect panel draw (the panel-draw seam:
        // effects/${slug}/android/${Name}Panel.kt) — the ONLY per-effect
        // Kotlin; the backbone redraws + uploads it every frame.
        draw = ::draw${Name}Panel,
    )`;
  } else if (isSprite) {
    configDecl = `private val config: PassConfig = dopePassConfig(
        doc, ${SLUG}_VERTEX_SRC, ${SLUG}_FRAGMENT_SRC, plan,
        // The hand-written per-effect SPRITE-PANEL draw (the panel-draw seam:
        // effects/${slug}/android/${Name}Panel.kt) — the ONLY per-effect Kotlin;
        // a PASS hybrid whose panel binds at its render.panel unit ALONGSIDE the
        // baked-SDF aux. The backbone redraws + uploads it every frame.
        draw = ::draw${Name}Panel,
    )`;
  }
  let numberImport = "";
  let uniformArrayImport = "";
  if (frameArrays) {
    const { entryName, params, arrays } = frameArrays;
    const reserved = RESERVED_LOGIC_ARGS.kotlin;
    if (params.some((p) => !reserved[p])) numberImport = "import ai.dopamine.core.number\n";
    uniformArrayImport = "import ai.dopamine.gl.UniformArray\n";
    const args = params
      .map((p) => reserved[p] ?? `${p} = params.number("${p}")`)
      .map((a) => `                ${a},`)
      .join("\n");
    const uniformArrays = arrays
      .map((a) => `                UniformArray("${a.web}", ${a.size}, out.${a.name}),`)
      .join("\n");
    configDecl = `private val config: PassConfig = dopePassConfig(
        doc, ${SLUG}_VERTEX_SRC, ${SLUG}_FRAGMENT_SRC, plan,
        // The generated ${Name}Renderer (transpiled from the single web logic
        // module) precomputes the frame geometry; \`binding.arrays\` maps its
        // bundle onto the named uniform arrays.
        frameArrays = { info, params, geom ->
            val out = ${entryName}(
${args}
            )
            listOf(
${uniformArrays}
            )
        },
    )`;
  }
  const handNote = isSprite
    ? `The ONLY hand-written Kotlin is the Canvas SPRITE-PANEL
// draw (${Name}Panel.kt — a PASS hybrid whose panel binds at its render.panel
// unit ALONGSIDE the baked-SDF aux; panel geometry is code by design); else`
    : isPanelKind
      ? `The ONLY hand-written Kotlin is the Canvas panel draw
// (${Name}Panel.kt — panel geometry is code by design); everything else that`
      : "This effect ships NO hand-written Kotlin: everything that";
  const configFn = isPanelKind ? "dopePanelConfig" : "dopePassConfig";
  const runnerKind = isPanelKind ? "panel" : "pass";
  return `${genHeader(slug)}
//
// ${Name} as a Dopamine effect on the Android backbone — the DATA-DRIVEN
// registration shim. ${handNote}
// isn't the GLSL lives in ${slug}.dope.json — the mood→params mapping + palette
// (the loader), the per-frame logic (\`tempo.frame\`), \`render.shadowHeightFrac\`,
// \`render.consts\`, \`render.config\`, \`tempo.reducedMotion\`, any \`tempo.loop\`
// contract and the uniform \`binding\` contract. \`dopePassPlan\` + \`${configFn}\`
// interpret that data through the generic ${runnerKind} runner. (The shader Kotlin is
// toolchain-generated from the same canonical web GLSL as the MSL.) The \`.dope\`
// bytes are the SAME as the web's (byte-parity proven by the 192-case grid).

package ${namespace}

import ai.dopamine.core.DopeDoc
import ai.dopamine.core.DopeException
import ai.dopamine.core.DopePassPlan
import ai.dopamine.core.DopeResolveInput
import ai.dopamine.core.DopeValue
import ai.dopamine.core.EffectRegistry
import ai.dopamine.core.dopePassPlan
${numberImport}import ai.dopamine.core.parseDope
import ai.dopamine.core.resolveDopeParams
import ai.dopamine.gl.DrawableEffect
import ai.dopamine.gl.EffectContext
import ai.dopamine.gl.EffectInstance
import ai.dopamine.gl.${isPanelKind ? "PanelConfig" : "PassConfig"}
${uniformArrayImport}import ai.dopamine.gl.${isPanelKind ? "createPanelInstance" : "createPassInstance"}
import ai.dopamine.gl.${configFn}
import android.content.Context

class ${Name}(context: Context) : DrawableEffect {
    override val name: String = "${slug}"

    // Load the bundled \`.dope\` (the EXACT web bytes) from the merged APK assets —
    // proving the data spine is shared verbatim across platforms.
    val doc: DopeDoc = parseDope(
        context.assets.open("${slug}.dope.json").bufferedReader(Charsets.UTF_8).use { it.readText() },
    )

    // The whole factory (resolve consts/scatter, uniforms/bindings, the
    // per-frame logic, shadow height, reduced motion, the loop contract) is
    // data: ${slug}.dope.json interpreted by the core backbone.
    private val plan: DopePassPlan = dopePassPlan(doc)
    private val scatterKey: String =
        plan.scatterKey ?: throw DopeException("dope: \${doc.id} has no binding.scatterKey")
    ${configDecl}

    override fun resolve(feeling: DopeResolveInput): Map<String, DopeValue> =
        resolveDopeParams(doc, feeling, consts = plan.consts, scatterKey = scatterKey)

    override fun create(params: Map<String, DopeValue>, ctx: EffectContext): EffectInstance =
        ${isPanelKind ? "createPanelInstance" : "createPassInstance"}(config, params, ctx)

    override val reducedMotionPeakMs: Double? = plan.reducedMotionPeakMs
    override val reducedMotionHoldMs: Double? = plan.reducedMotionHoldMs

    // The CONTINUOUS-loop contract (\`tempo.loop\`), null for one-shots: the
    // conductor re-arms a looping effect until the host stops the play handle.
    override val loop = doc.loop

    companion object {
        /** Construct + register the effect (needs a Context for the \`.dope\` asset). */
        fun register(context: Context): ${Name} {
            val fx = ${Name}(context.applicationContext)
            EffectRegistry.register(fx)
            return fx
        }
    }
}
`;
}
