/**
 * dopamine toolchain — SwiftPM package emitter.
 *
 * Turns a single effect folder (`effects/<id>/`) into a STANDALONE, installable
 * SwiftPM package under `dist/swift/<Module>/`:
 *
 *   dist/swift/DopamineEffectComic/
 *     Package.swift                         (generated)
 *     Sources/DopamineEffectComic/
 *       *.swift                             (the hand-written per-platform sources)
 *       <Name>Uniforms.swift                (GENERATED binding struct + packer)
 *       Shaders/*.metal                     (hand-written shader + shared look lib)
 *       Shaders/<Name>Uniforms.metal        (GENERATED MSL struct)
 *       Resources/<id>.dope.json            (a REAL embedded copy of the data spine)
 *
 * The package depends on `DopamineCore` (a path dep to the monorepo's swift/
 * package for local builds; an external author points this at a published
 * DopamineCore). The output is a real package a Swift developer can `swift build`
 * / add as a SwiftPM dependency — NOT a symlink into this repo.
 */

import { readFile, readdir } from "node:fs/promises";
import { join, relative } from "node:path";
import { buildFields, emitSwift, emitMSL } from "./uniforms.mjs";

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/** Emit the generated `Package.swift` for a standalone effect package. */
function emitPackageSwift({ module, id, corePath, core, platforms }) {
  const plats = (platforms ?? ["iOS(.v15)", "macOS(.v12)"]).map((p) => `.${p}`).join(", ");
  const dep =
    core?.mode === "url"
      ? `.package(url: "${core.url}", from: "${core.from ?? "0.0.0"}")`
      : `.package(name: "${core?.package ?? "Dopamine"}", path: "${corePath}")`;
  const pkgName = core?.package ?? "Dopamine";
  const product = core?.product ?? "DopamineCore";
  return `// swift-tools-version:5.9
// @generated by @dopamine/build from effects/${id} — do not edit.
// A STANDALONE, SwiftPM-installable package: real bundled ${id}.dope.json + the
// hand-written sources + the generated uniform struct, depending on ${product}.
import PackageDescription

let package = Package(
    name: "${module}",
    platforms: [${plats}],
    products: [
        .library(name: "${module}", targets: ["${module}"]),
    ],
    dependencies: [
        ${dep},
    ],
    targets: [
        .target(
            name: "${module}",
            dependencies: [.product(name: "${product}", package: "${pkgName}")],
            resources: [
                .copy("Resources/${id}.dope.json"),
                .process("Shaders"),
            ]
        ),
    ]
)
`;
}

/**
 * Generate the SwiftPM package artifacts for one effect.
 * @returns {Promise<Array<{ path: string, content: string }>>} paths are relative
 *          to the dist output root (e.g. `swift/DopamineEffectComic/Package.swift`).
 */
export async function generateSwiftPackage({ root, effectDirAbs, manifest, dope, dataText, outDir }) {
  const id = manifest.id;
  const Name = pascal(id);
  const sw = manifest.platforms?.swift ?? {};
  const module = sw.module ?? `DopamineEffect${Name}`;
  const srcAbs = join(effectDirAbs, sw.sources ?? "swift");
  const fields = buildFields(dope, manifest.binding ?? {});

  const pkgRel = join("swift", module);
  const srcRel = join(pkgRel, "Sources", module);
  const out = [];

  // (1) hand-written Swift sources (top-level *.swift in the folder's swift/ dir)
  for (const name of (await readdir(srcAbs)).sort()) {
    if (name.endsWith(".swift")) {
      out.push({ path: join(srcRel, name), content: await readFile(join(srcAbs, name), "utf8") });
    }
  }

  // (2) hand-written shaders (Shaders/* — the .metal body + the shared look lib)
  const shadersAbs = join(srcAbs, "Shaders");
  let shaderNames = [];
  try { shaderNames = (await readdir(shadersAbs)).sort(); } catch { /* no shaders */ }
  for (const name of shaderNames) {
    out.push({ path: join(srcRel, "Shaders", name), content: await readFile(join(shadersAbs, name), "utf8") });
  }

  // (3) generated binding glue — the Swift struct + packer and the MSL struct,
  //     from ONE source (the .dope render.params + the binding manifest).
  out.push({ path: join(srcRel, `${Name}Uniforms.swift`), content: emitSwift(id, fields) });
  out.push({ path: join(srcRel, "Shaders", `${Name}Uniforms.metal`), content: emitMSL(id, fields) });

  // (4) a REAL embedded copy of the data spine (this is the publishable artifact).
  out.push({ path: join(srcRel, "Resources", `${id}.dope.json`), content: dataText });

  // (5) the generated Package.swift (standalone + installable).
  const corePath = relative(join(outDir, pkgRel), join(root, sw.core?.path ?? "swift")) || ".";
  out.push({
    path: join(pkgRel, "Package.swift"),
    content: emitPackageSwift({ module, id, corePath, core: sw.core, platforms: sw.platforms }),
  });

  return out;
}
