/**
 * dopamine toolchain — SwiftPM package emitter.
 *
 * Turns a single effect folder into a STANDALONE, installable SwiftPM package
 * under `dist/swift/<Module>/`:
 *
 *   dist/swift/DopamineEffectComic/
 *     Package.swift                         (generated)
 *     Sources/DopamineEffectComic/
 *       *.swift                             (hand-written per-platform sources)
 *       <Name>Uniforms.swift                (GENERATED binding struct + packer)
 *       Shaders/*.metal                     (hand-written shader + shared look lib)
 *       Shaders/<Name>Uniforms.metal        (GENERATED MSL struct)
 *       Resources/<slug>.dope.json          (the PORTABLE embedded data spine)
 *
 * Depends on `DopamineCore` (path dep to the monorepo for local builds; an
 * external author points `x-build.swift.core` at a published DopamineCore). The
 * output is a real package a Swift dev can `swift build` / depend on.
 */

import { readFile, readdir } from "node:fs/promises";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { buildFields, emitSwift, emitMSL } from "./uniforms.mjs";
import { glslToMSL, buildUniformMap } from "./shader.mjs";
import { loadWebGLSL } from "./glsl-load.mjs";
import { assertFactoryGeneratable, buildFrameArraysSpec, emitSwiftFactory, emitSwiftBundle } from "./factory.mjs";
import { emitSwiftLogicParityTests } from "./logic.mjs";

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * The shared MSL "look" library, kept in ONE canonical place (the toolchain's
 * `assets/`) instead of a byte-identical copy hand-maintained in every effect's
 * `swift/Shaders/`. The Android port already holds the look once (`Look.kt`); this
 * is the Swift analog. The toolchain injects it into every effect's `dist/` package.
 */
const LOOK_METAL_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "assets", "DopamineLook.metal");

/** Emit the generated `Package.swift` for a standalone effect package. */
function emitPackageSwift({ module, slug, corePath, core, platforms, hasFonts, hasLogicTests }) {
  const plats = (platforms ?? ["iOS(.v15)", "macOS(.v12)"]).map((p) => `.${p}`).join(", ");
  const pkgName = core?.package ?? "Dopamine";
  const product = core?.product ?? "DopamineCore";
  const dep =
    core?.mode === "url"
      ? `.package(url: "${core.url}", from: "${core.from ?? "0.0.0"}")`
      : `.package(name: "${pkgName}", path: "${corePath}")`;
  // The bundled display faces (ttf, converted from the shared woff2) ship as a
  // copied resource directory only when the effect declares fonts.
  const fontsRes = hasFonts ? `\n                .copy("Resources/fonts"),` : "";
  // Effects with generated per-frame-geometry logic carry a GENERATED parity test
  // target (Linux-runnable: the generated renderer is pure Swift) replaying the
  // committed web-dumped fixture.
  const testTarget = hasLogicTests
    ? `
        .testTarget(
            name: "${module}Tests",
            dependencies: ["${module}"],
            resources: [
                .copy("Resources/${slug}-logic-parity.json"),
            ]
        ),`
    : "";
  return `// swift-tools-version:5.9
// @generated by @dopaminefx/build from effects/${slug} — do not edit.
// A STANDALONE, SwiftPM-installable package: real bundled ${slug}.dope.json + the
// hand-written sources + the generated uniform struct, depending on ${product}.
import PackageDescription

let package = Package(
    name: "${module}",
    platforms: [${plats}],
    products: [
        .library(name: "${module}", targets: ["${module}"]),
    ],
    dependencies: [
        ${dep},
    ],
    targets: [
        .target(
            name: "${module}",
            dependencies: [.product(name: "${product}", package: "${pkgName}")],
            resources: [
                .copy("Resources/${slug}.dope.json"),${fontsRes}
                .process("Shaders"),
            ]
        ),${testTarget}
    ]
)
`;
}

/**
 * Generate the SwiftPM package artifacts for one loaded effect (`eff` from
 * build.mjs `loadEffect`: { dir, doc, slug, dope }).
 * @returns {Promise<Array<{ path: string, content: string }>>} dist-relative paths.
 */
export async function generateSwiftPackage({ root, eff, outDir, fonts = [], logic = null }) {
  const { dir, doc, slug, dope } = eff;
  const Name = pascal(slug);
  const sw = doc["x-build"].swift;
  const module = sw.module ?? `DopamineEffect${Name}`;
  const srcAbs = join(dir, sw.sources ?? "swift");
  const fields = buildFields(doc, doc.binding ?? {});

  const pkgRel = join("swift", module);
  const srcRel = join(pkgRel, "Sources", module);
  const out = [];

  // (1) the Swift sources. An effect with a hand-written FACTORY (`<Name>.swift`
  //     — a code-shaped hook, a hand pass config) ships its swift/ dir verbatim.
  //     When no hand factory exists, the factory shell + resource-bundle
  //     accessor are GENERATED from the `.dope` (factory.mjs): a FULLY
  //     DECLARATIVE effect ships NO swift/ dir at all, and a PANEL effect
  //     (`render.panel`) ships ONLY its `<Name>Panel.swift` draw — the
  //     panel-draw seam the generated factory wires (`draw<Name>Panel`). When
  //     the effect declares generated per-frame-geometry logic
  //     (`x-build.logic`), its `<Name>Renderer.swift` is TRANSPILED from the
  //     single web TS source — never hand-shipped.
  const generatedRendererFile = logic ? `${Name}Renderer.swift` : null;
  let handNames = [];
  try { handNames = (await readdir(srcAbs)).sort(); } catch { /* no swift/ dir */ }
  const hand = handNames.filter((n) => n.endsWith(".swift") && n !== generatedRendererFile);
  for (const name of hand) {
    out.push({ path: join(srcRel, name), content: await readFile(join(srcAbs, name), "utf8") });
  }
  if (!hand.includes(`${Name}.swift`)) {
    assertFactoryGeneratable(doc, slug, "swift");
    // The panel MODE drives which generic config the factory wraps:
    //   - "panel"  — a panel-KIND effect (kind:"panel"): the whole-content
    //     Canvas panel runner (DopePanelPassConfig), panel pinned at texture(0).
    //   - "sprite" — a PASS hybrid with a dynamic sprite panel at an ARBITRARY
    //     unit ALONGSIDE the baked-SDF aux (DopeSpritePanelPassConfig:
    //     solarbloom's motes panel at texture(3) + the ✓ SDF at texture(1)).
    //   - "none"   — a pure pass effect (DopePassConfig).
    const panelMode = !doc.render?.panel ? "none" : doc.kind === "panel" ? "panel" : "sprite";
    if (panelMode !== "none" && !hand.includes(`${Name}Panel.swift`)) {
      throw new Error(
        `dopamine: effects/${slug} declares render.panel but has no swift/${Name}Panel.swift — ` +
          `the generated factory wires the hand-written draw${Name}Panel (the panel-draw seam).`,
      );
    }
    // A panel-KIND effect's panel MUST live at texture(0) (the Metal panel slot
    // the panel runner binds); a SPRITE panel binds at an arbitrary unit (the
    // generalized pass runner reads render.panel.texture), so it has no such
    // constraint — texture(0) stays free for any aux the pass shader declares.
    if (panelMode === "panel" && (doc.render.panel.texture ?? 0) !== 0) {
      throw new Error(`dopamine: effects/${slug} render.panel.texture must be 0 for a panel-kind effect (the Metal panel slot)`);
    }
    out.push({ path: join(srcRel, `${Name}.swift`), content: emitSwiftFactory(slug, buildFrameArraysSpec(doc, slug, logic), panelMode) });
    if (!hand.includes(`${Name}Bundle.swift`)) {
      out.push({ path: join(srcRel, `${Name}Bundle.swift`), content: emitSwiftBundle(slug) });
    }
  }

  // (2) the bespoke per-effect shader. When the effect declares a generated MSL
  //     (`x-build.shader.generateMSL`), the `.metal` is TRANSPILED from the single
  //     canonical web GLSL source — no hand-ported `.metal` to drift; otherwise the
  //     hand-written `Shaders/*.metal` is copied. The shared look lib is NOT kept
  //     here — it's injected once from the toolchain asset (2b).
  const shaderCfg = doc["x-build"].shader;
  if (shaderCfg?.generateMSL) {
    const { fragment } = await loadWebGLSL(root, dir, shaderCfg);
    const samplers = doc.binding?.samplers ?? [];
    const arrays = doc.binding?.arrays ?? [];
    const msl = glslToMSL({ slug, fragment, uniformMap: buildUniformMap(fields), samplers, arrays });
    out.push({ path: join(srcRel, "Shaders", `${Name}.metal`), content: msl });
  } else {
    const shadersAbs = join(srcAbs, "Shaders");
    let shaderNames = [];
    try { shaderNames = (await readdir(shadersAbs)).sort(); } catch { /* no shaders */ }
    for (const name of shaderNames) {
      if (name === "DopamineLook.metal") continue;
      out.push({ path: join(srcRel, "Shaders", name), content: await readFile(join(shadersAbs, name), "utf8") });
    }
  }

  // (2b) the shared MSL look library — one canonical source → every package.
  out.push({ path: join(srcRel, "Shaders", "DopamineLook.metal"), content: await readFile(LOOK_METAL_PATH, "utf8") });

  // (2c) the generated per-frame-geometry renderer (x-build.logic): pure Swift,
  //      transpiled from the single web TS source (logic.mjs) — plus, when the
  //      effect commits a parity fixture, a GENERATED XCTest target replaying the
  //      web-dumped grid (Linux-runnable; `swift test` in the dist package).
  if (logic) {
    out.push({ path: join(srcRel, `${Name}Renderer.swift`), content: logic.swift });
    if (logic.fixture) {
      const testRel = join(pkgRel, "Tests", `${module}Tests`);
      out.push({
        path: join(testRel, `${Name}LogicParityTests.swift`),
        content: emitSwiftLogicParityTests(logic.model, slug, module),
      });
      out.push({ path: join(testRel, "Resources", `${slug}-logic-parity.json`), content: logic.fixture });
    }
  }

  // (3) generated binding glue — the Swift struct + packer and the MSL struct,
  //     from ONE source (the .dope render.params + the binding contract).
  out.push({ path: join(srcRel, `${Name}Uniforms.swift`), content: emitSwift(slug, fields) });
  out.push({ path: join(srcRel, "Shaders", `${Name}Uniforms.metal`), content: emitMSL(slug, fields) });

  // (4) the PORTABLE embedded data spine (toolchain keys stripped) — the shipped,
  //     standalone-safe runtime doc, identical across platforms.
  out.push({ path: join(srcRel, "Resources", `${slug}.dope.json`), content: dope });

  // (4b) the bundled display faces (ttf, converted from the shared woff2) — the
  //      panel registers these via Core Text from Bundle.module's Resources/fonts.
  for (const f of fonts) {
    out.push({ path: join(srcRel, "Resources", "fonts", f.name), content: f.content });
  }

  // (5) the generated Package.swift (standalone + installable).
  const corePath = relative(join(outDir, pkgRel), join(root, sw.core?.path ?? "swift")) || ".";
  out.push({
    path: join(pkgRel, "Package.swift"),
    content: emitPackageSwift({
      module, slug, corePath, core: sw.core, platforms: sw.platforms,
      hasFonts: fonts.length > 0, hasLogicTests: !!logic?.fixture,
    }),
  });

  return out;
}
