/**
 * dopamine toolchain — uniform-binding generator.
 *
 * Emits, from ONE source of truth (an effect's `.dope` `render.params` + its
 * binding manifest), the three platform binding artifacts:
 *   (a) MSL   — `struct <Name>Uniforms { … }` the `.metal` `#include`s.
 *   (b) Swift — the `<Name>Uniforms` struct + `pack<Name>Uniforms(...)` packer.
 *   (c) Web   — the `u<Name>` uniform-name superset (the GLSL declares these).
 *
 * This is the logic that lived in `scripts/gen-uniforms.mjs`, re-homed into the
 * cross-platform build tool and driven by each effect FOLDER's `effect.json`
 * (`binding`) instead of one monolithic EFFECTS map — so an effect package is
 * self-describing. Output is kept BYTE-IDENTICAL to gen-uniforms during the
 * transition (the swift.yml staleness gate + the committed files are unchanged);
 * the toolchain test asserts that byte-for-byte.
 */

// Kept verbatim from scripts/gen-uniforms.mjs so generated bytes match during the
// move. (Once effects/<id>/ is the SOLE source of truth this header re-points at
// the toolchain; until then the existing files are still gen-uniforms' to own.)
const GEN_HEADER = "// @generated by scripts/gen-uniforms.mjs — do not edit";

// The standard uniform set the pass/panel runner always provides, in the EXACT
// order `StandardUniforms` (Swift) / the MSL struct declare them. Mirrors
// framework/pass-runner.ts `STANDARD` + pass-common `STANDARD_COMMON`.
export const STANDARD = [
  { name: "resolution", type: "float2", web: "uResolution" },
  { name: "origin", type: "float2", web: "uOrigin" },
  { name: "target", type: "float2", web: "uTarget" },
  { name: "life", type: "float", web: "uLife" },
  { name: "timeS", type: "float", web: "uTimeS" },
  { name: "loopS", type: "float", web: "uLoopS" },
  { name: "phase", type: "float", web: "uPhase" },
  { name: "style", type: "float", web: "uStyle" },
  { name: "amp", type: "float", web: "uAmp" },
  { name: "c0", type: "float3", web: "uC0" },
  { name: "c1", type: "float3", web: "uC1" },
  { name: "c2", type: "float3", web: "uC2" },
  { name: "shadow", type: "float", web: "uShadow" },
  { name: "shadowOffset", type: "float2", web: "uShadowOffset" },
  { name: "shadowSoft", type: "float", web: "uShadowSoft" },
  { name: "shadowStrength", type: "float", web: "uShadowStrength" },
  // Backdrop relative luminance (0 dark .. 1 white) the overlay composites
  // against, driving the light-out saturation/presence boost (dopLightOut). 0 by
  // default ⇒ no boost ⇒ the dark/legacy look is unchanged. Set by the host
  // runner from the public backdrop option; the web bakes it as a literal, the
  // native stacks read it from this uniform.
  { name: "backdropLum", type: "float", web: "uBackdropLum" },
];

const MSL_TYPE = { float: "float", float2: "float2", float3: "float3" };
const SWIFT_TYPE = { float: "Float", float2: "SIMD2<Float>", float3: "SIMD3<Float>" };
const SWIFT_ZERO = { float: "0", float2: "SIMD2<Float>(0, 0)", float3: "SIMD3<Float>(0, 0, 0)" };

/** `bloomRadius` → `uBloomRadius` (the web `u<Name>` convention). */
const cap = (s) => `u${s.charAt(0).toUpperCase()}${s.slice(1)}`;

function pascal(name) {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/**
 * Build the ordered field list for an effect from its `.dope` + binding manifest.
 * Order (the contract the shader's `#include`d struct relies on):
 *   standard → .dope render.params (minus excluded) → scatter key → frame extras.
 */
export function buildFields(dope, binding) {
  const fields = [];
  // (1) standard half — copied straight from StandardUniforms.
  for (const s of STANDARD) fields.push({ ...s, kind: "standard" });

  // (2) the effect's own render.params, in authored `.dope` order, skipping the
  // non-uniform ones. `int` and `float` both pack as a single Metal float.
  const params = dope.render?.params ?? {};
  const exclude = binding.excludeParams ?? [];
  for (const [name, spec] of Object.entries(params)) {
    if (exclude.includes(name)) continue;
    if (name === binding.scatterKey) continue; // appended explicitly below
    fields.push({ name, type: "float", web: cap(name), kind: "param", dopeType: spec.type });
  }

  // (3) the scatter key (resolved, seed-keyed; the shader reads it by name).
  if (binding.scatterKey) {
    fields.push({
      name: binding.scatterKey,
      type: "float",
      web: binding.scatterWeb ?? cap(binding.scatterKey),
      kind: "scatter",
    });
  }

  // (4) per-frame + plumbing extras (filled by frame()/host, not the loader).
  for (const e of binding.extras ?? []) fields.push({ ...e, kind: "extra" });
  return fields;
}

export function emitMSL(effect, fields) {
  const Name = pascal(effect);
  const lines = [];
  lines.push(GEN_HEADER);
  lines.push(`// MSL uniform struct for the ${effect} fragment shader. \`#include\` this from`);
  lines.push(`// the \`.metal\` and read \`constant ${Name}Uniforms &u [[buffer(0)]]\`. Field`);
  lines.push(`// ORDER/types match the Swift \`${Name}Uniforms\` packer (gen-uniforms emits both).`);
  lines.push(`#ifndef ${effect.toUpperCase()}_UNIFORMS_H`);
  lines.push(`#define ${effect.toUpperCase()}_UNIFORMS_H`);
  lines.push(`#include <metal_stdlib>`);
  lines.push(`using namespace metal;`);
  lines.push(``);
  lines.push(`struct ${Name}Uniforms {`);
  let lastKind = null;
  const kindLabel = {
    standard: "    // --- standard (StandardUniforms, in declared order) ---",
    param: `    // --- ${effect} render.params (auto-bound by name) ---`,
    scatter: "    // --- scatter key (seed-keyed; read by name) ---",
    extra: "    // --- frame extras + plumbing (filled by frame()/host) ---",
  };
  for (const f of fields) {
    if (f.kind !== lastKind) { lines.push(kindLabel[f.kind]); lastKind = f.kind; }
    const note = f.note ? `   // ${f.note}` : "";
    lines.push(`    ${MSL_TYPE[f.type].padEnd(6)} ${f.name};${note}`);
  }
  lines.push(`};`);
  lines.push(`#endif`);
  lines.push(``);
  return lines.join("\n");
}

export function emitSwift(effect, fields) {
  const Name = pascal(effect);
  const lines = [];
  lines.push(GEN_HEADER);
  lines.push(`// Swift uniform struct + packer for ${effect}. Its memory layout MUST match`);
  lines.push(`// \`struct ${Name}Uniforms\` in Shaders/${Name}Uniforms.metal — gen-uniforms`);
  lines.push(`// emits both from the same field list, so they cannot drift.`);
  lines.push(`//`);
  lines.push(`// The GLSL→MSL binding seam, datafied: the web's per-name \`gl.uniform*\` becomes`);
  lines.push(`// this one packed struct, filled from the resolved \`.dope\` param bag by name.`);
  lines.push(`#if canImport(Metal)`);
  lines.push(`import simd`);
  lines.push(`import DopamineCore`);
  lines.push(``);
  lines.push(`public struct ${Name}Uniforms {`);
  let lastKind = null;
  const kindLabel = {
    standard: "    // standard (matches StandardUniforms order)",
    param: `    // ${effect} render.params (auto-bound by name from the resolved bag)`,
    scatter: "    // scatter key (seed-keyed)",
    extra: "    // frame extras + plumbing (filled by frame()/host)",
  };
  for (const f of fields) {
    if (f.kind !== lastKind) { lines.push(kindLabel[f.kind]); lastKind = f.kind; }
    lines.push(`    public var ${f.name}: ${SWIFT_TYPE[f.type]} = ${SWIFT_ZERO[f.type]}`);
  }
  lines.push(`    public init() {}`);
  lines.push(`}`);
  lines.push(``);

  lines.push(`/// Pack the resolved bag → the struct. The standard half is copied from`);
  lines.push(`/// \`StandardUniforms\`; each named scalar maps to its struct field (the web's`);
  lines.push(`/// \`u<Name>\` auto-bind); \`extras\` carries the frame()/host values.`);
  lines.push(`public func pack${Name}Uniforms(`);
  lines.push(`    standard s: StandardUniforms,`);
  lines.push(`    params: [String: DopeValue],`);
  lines.push(`    extras: [String: Double]`);
  lines.push(`) -> ${Name}Uniforms {`);
  lines.push(`    var u = ${Name}Uniforms()`);
  lines.push(`    // standard half`);
  for (const f of fields.filter((x) => x.kind === "standard")) {
    lines.push(`    u.${f.name} = s.${f.name}`);
  }
  lines.push(`    // resolved scalar params (by name)`);
  lines.push(`    func f(_ k: String) -> Float { if case let .number(v)? = params[k] { return Float(v) }; return 0 }`);
  for (const f of fields.filter((x) => x.kind === "param" || x.kind === "scatter")) {
    lines.push(`    u.${f.name} = f("${f.name}")`);
  }
  lines.push(`    // frame extras + plumbing`);
  for (const f of fields.filter((x) => x.kind === "extra")) {
    lines.push(`    u.${f.name} = Float(extras["${f.name}"] ?? 0)`);
  }
  lines.push(`    return u`);
  lines.push(`}`);
  lines.push(`#endif`);
  lines.push(``);
  return lines.join("\n");
}

export function emitWeb(effect, fields, binding) {
  const standardWeb = STANDARD.map((s) => s.web);
  const effectUniforms = [
    ...fields.filter((x) => x.kind !== "standard").map((x) => x.web),
    ...(binding.samplers ?? []).map((s) => (typeof s === "string" ? s : s.web)),
  ];
  return JSON.stringify(
    {
      _generated: "scripts/gen-uniforms.mjs — do not edit",
      effect,
      standardUniforms: standardWeb,
      effectUniforms,
      allUniforms: [...standardWeb, ...effectUniforms],
    },
    null,
    2,
  ) + "\n";
}
