// swift-tools-version:5.9
// @generated by @dopaminefx/build — do not edit.
// The AGGREGATE Dopamine SwiftPM package: DopamineCore + every effect as a
// library product, installable by git URL + semver tag. Generated by
// scripts/swift-aggregate.mjs onto the release tag (never committed to main).
import PackageDescription

let package = Package(
    name: "Dopamine",
    platforms: [.iOS(.v15), .macOS(.v12)],
    products: [
        .library(name: "DopamineCore", targets: ["DopamineCore"]),
        .library(name: "DopamineEffectAurora", targets: ["DopamineEffectAurora"]),
        .library(name: "DopamineEffectCheckmate", targets: ["DopamineEffectCheckmate"]),
        .library(name: "DopamineEffectComic", targets: ["DopamineEffectComic"]),
        .library(name: "DopamineEffectConfetti", targets: ["DopamineEffectConfetti"]),
        .library(name: "DopamineEffectDots", targets: ["DopamineEffectDots"]),
        .library(name: "DopamineEffectFail", targets: ["DopamineEffectFail"]),
        .library(name: "DopamineEffectHalo", targets: ["DopamineEffectHalo"]),
        .library(name: "DopamineEffectHeartburst", targets: ["DopamineEffectHeartburst"]),
        .library(name: "DopamineEffectInkstroke", targets: ["DopamineEffectInkstroke"]),
        .library(name: "DopamineEffectLightning", targets: ["DopamineEffectLightning"]),
        .library(name: "DopamineEffectRipple", targets: ["DopamineEffectRipple"]),
        .library(name: "DopamineEffectSolarbloom", targets: ["DopamineEffectSolarbloom"]),
    ],
    targets: [
        .target(name: "DopamineCore", path: "swift/Sources/DopamineCore"),
        .target(
            name: "DopamineEffectAurora",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectAurora/Sources/DopamineEffectAurora",
            resources: [
                .copy("Resources/aurora.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectCheckmate",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectCheckmate/Sources/DopamineEffectCheckmate",
            resources: [
                .copy("Resources/checkmate.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectComic",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectComic/Sources/DopamineEffectComic",
            resources: [
                .copy("Resources/comic.dope.json"),
                .copy("Resources/fonts"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectConfetti",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectConfetti/Sources/DopamineEffectConfetti",
            resources: [
                .copy("Resources/confetti.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectDots",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectDots/Sources/DopamineEffectDots",
            resources: [
                .copy("Resources/dots.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectFail",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectFail/Sources/DopamineEffectFail",
            resources: [
                .copy("Resources/fail.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectHalo",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectHalo/Sources/DopamineEffectHalo",
            resources: [
                .copy("Resources/halo.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectHeartburst",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectHeartburst/Sources/DopamineEffectHeartburst",
            resources: [
                .copy("Resources/heartburst.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectInkstroke",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectInkstroke/Sources/DopamineEffectInkstroke",
            resources: [
                .copy("Resources/inkstroke.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectLightning",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectLightning/Sources/DopamineEffectLightning",
            resources: [
                .copy("Resources/lightning.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectRipple",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectRipple/Sources/DopamineEffectRipple",
            resources: [
                .copy("Resources/ripple.dope.json"),
                .process("Shaders"),
            ]
        ),
        .target(
            name: "DopamineEffectSolarbloom",
            dependencies: ["DopamineCore"],
            path: "dist/swift/DopamineEffectSolarbloom/Sources/DopamineEffectSolarbloom",
            resources: [
                .copy("Resources/solarbloom.dope.json"),
                .process("Shaders"),
            ]
        ),
    ]
)
