// @generated by @dopaminefx/build from the web GLSL (effects/confetti/web/src/confetti-shader.ts).
// Android OpenGL ES 3.0 == GLSL ES 3.00 (the WebGL2 dialect), so the shader body is
// the web source verbatim; the look chunks come from dopamine-core/Look.kt ONCE (the
// ${GLSL_*} refs below), and the only emit change is dopLightOut (premultiplied light).
// DO NOT EDIT — regenerate via `node tools/dopamine/src/cli.mjs build`.
package ai.dopamine.effect.confetti

import ai.dopamine.core.GLSL_CONSTANTS
import ai.dopamine.core.GLSL_DITHER
import ai.dopamine.core.GLSL_HASH
import ai.dopamine.core.GLSL_LIGHT_OUT
import ai.dopamine.core.GLSL_TONEMAP_ACES

val CONFETTI_VERTEX_SRC: String = """#version 300 es
out vec2 vUv;
void main() {
  // Single full-screen triangle from gl_VertexID — no vertex buffers needed.
  vec2 pos = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));
  vUv = pos;
  gl_Position = vec4(pos * 2.0 - 1.0, 0.0, 1.0);
}"""

val CONFETTI_FRAGMENT_SRC: String = """#version 300 es
precision highp float;
in vec2 vUv;
out vec4 fragColor;

uniform sampler2D uPanel;     // RGB = accumulated per-piece lit colour × fade
uniform vec2  uResolution;    // device pixels
uniform float uAmp;           // envelope amplitude (peaks > 1) — overall brightness
uniform float uTimeS;         // elapsed seconds (snapped "on twos" with style)
uniform float uExposure;
uniform float uStyle;         // 0..1 photoreal paper -> flat cel shapes
uniform float uShadow;        // 0 = light pass (screen), 1 = shadow pass (multiply)
uniform vec2  uShadowOffset;  // device-px offset of the cast silhouette
uniform float uShadowSoft;    // penumbra softness in device px (blur tap radius)
uniform float uShadowStrength;// 0..1 max darkening of the multiply layer
uniform vec3  uC0;

${GLSL_CONSTANTS}
${GLSL_HASH}
${GLSL_TONEMAP_ACES}
${GLSL_DITHER}
${GLSL_LIGHT_OUT}

void main() {
  vec2 frag = vUv * uResolution;

  // ---- SHADOW pass (multiply layer) --------------------------------------
  // A cheap soft drop-shadow: ring-blur the panel's mass at a sample point pushed
  // against the light offset. White = no shadow; darker = cast silhouette.
  if (uShadow > 0.5) {
    vec2 px = 1.0 / uResolution;
    vec2 souv = vUv - uShadowOffset * px;
    float occ = 0.0;
    for (int i = 0; i < 8; i++) {
      float a = float(i) / 8.0 * TAU;
      vec2 o = vec2(cos(a), sin(a)) * uShadowSoft * px;
      vec2 tuv = souv + o;
      vec2 inb = step(vec2(0.0), tuv) * step(tuv, vec2(1.0));
      vec3 s = texture(uPanel, tuv).rgb;
      occ += (s.r + s.g + s.b) * (1.0 / 3.0) * inb.x * inb.y;
    }
    occ /= 8.0;
    float dark = clamp(occ * uAmp, 0.0, 1.0) * uShadowStrength;
    vec3 tint = mix(vec3(1.0), 0.6 + 0.4 * normalize(uC0 + 1e-3), 0.2);
    vec3 mul = mix(vec3(1.0), tint, dark);
    fragColor = dopLightOut(mul);
    return;
  }

  // ---- LIGHT pass --------------------------------------------------------
  // The panel already holds Σ(lit × fade) per piece; apply the global gain, then
  // the same filmic + cel + dither finish the original single-pass shader did.
  vec3 col = texture(uPanel, vUv).rgb * (uAmp * uExposure) * 1.35;

  col = tonemapACES(col * 0.85);

  // Cel posterize at the whimsy end: punch saturation + quantize into hard bands.
  if (uStyle > 0.001) {
    float l = dot(col, vec3(0.299, 0.587, 0.114));
    vec3 neon = clamp(l + (col - l) * 1.5, 0.0, 1.0);
    vec3 styled = mix(col, neon, 0.65);
    float bands = mix(40.0, 5.0, uStyle);
    styled = floor(styled * bands + 0.5) / bands;
    col = mix(col, styled, uStyle);
  }

  // Ordered dither to break screen-blend banding; faded toward the cel end.
  col = ditherAdd(col, frag, uTimeS, 1.0 - uStyle);

  fragColor = vec4(col, 1.0);
}"""
