// @generated by @dopaminefx/build from the web GLSL (effects/dots/web/src/dots-shader.ts).
// Android OpenGL ES 3.0 == GLSL ES 3.00 (the WebGL2 dialect), so the shader body is
// the web source verbatim; the look chunks come from dopamine-core/Look.kt ONCE (the
// ${GLSL_*} refs below), and the only emit change is dopLightOut (premultiplied light).
// DO NOT EDIT — regenerate via `node tools/dopamine/src/cli.mjs build`.
package ai.dopamine.effect.dots

import ai.dopamine.core.GLSL_CONSTANTS
import ai.dopamine.core.GLSL_DITHER
import ai.dopamine.core.GLSL_HASH
import ai.dopamine.core.GLSL_LIGHT_OUT
import ai.dopamine.core.GLSL_PALETTE_MIX
import ai.dopamine.core.GLSL_TONEMAP_ACES

val DOTS_VERTEX_SRC: String = """#version 300 es
out vec2 vUv;
void main() {
  // Single full-screen triangle from gl_VertexID — no vertex buffers needed.
  vec2 pos = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));
  vUv = pos;
  gl_Position = vec4(pos * 2.0 - 1.0, 0.0, 1.0);
}"""

val DOTS_FRAGMENT_SRC: String = """#version 300 es
precision highp float;
out vec4 fragColor;

uniform vec2  uResolution;    // device pixels
uniform vec2  uOrigin;        // row centre, gl coords (y up)
uniform float uAmp;           // STEADY periodic breathe gate (~0.85..1.0), not an envelope
uniform float uPhase;         // normalized loop phase [0,1) (tempo.loop) — drives ALL motion
uniform float uLoopS;         // seconds within the current loop (the dither's temporal seed)
uniform float uExposure;
uniform float uDotCount;      // number of dots in the row (clamped to MAX_DOTS)
uniform float uDotRadius;     // dot radius as a fraction of min viewport dim
uniform float uDotGap;        // centre-to-centre spacing as a fraction of min viewport dim
uniform float uBreathe;       // 0..1 breathe depth (radius/brightness sine swing)
uniform float uChase;         // 0..1+ sharpness of the traveling pulse (tighter = livelier)
uniform float uGlow;          // 0..1 ambient under-glow brightness
uniform float uStyle;         // 0..1 photoreal soft glow -> cel/flat discs (whimsy)
uniform float uShadow;        // 0 = light pass (screen), 1 = shadow pass (multiply)
uniform vec2  uShadowOffset;  // device-px offset of the cast silhouette (away from light)
uniform float uShadowSoft;    // penumbra softness in device px (blur tap radius)
uniform float uShadowStrength;// 0..1 max darkening of the multiply layer
uniform vec3  uC0;            // dot core color
uniform vec3  uC1;            // mid
uniform vec3  uC2;            // pulse accent

#define MAX_DOTS 7

${GLSL_CONSTANTS}
${GLSL_HASH}
${GLSL_PALETTE_MIX}
${GLSL_TONEMAP_ACES}
${GLSL_DITHER}
${GLSL_LIGHT_OUT}

// The live count, clamped to the compile-time cap so the loop bound is constant.
int dotCount(){
  return int(clamp(uDotCount, 1.0, float(MAX_DOTS)) + 0.5);
}

// The breathing dot radius. One slow sine per loop period swings the radius by
// ±uBreathe·radius around the base — the gentle pulse "breath". Periodic in
// uPhase, so it returns to its t=0 value at every seam.
float liveRadius(){
  return uDotRadius * (1.0 + sin(TAU * uPhase) * uBreathe * 0.45);
}

// The normalized x-centre of dot i: a row of dotCount dots, spaced uDotGap apart,
// centred on the origin (so the whole row is symmetric about x = 0).
float dotCenterX(int i, int count){
  float c = float(count);
  return (float(i) - (c - 1.0) * 0.5) * uDotGap;
}

// 0..1 "lit" weight of dot i under the traveling pulse. The pulse HEAD winds one
// full turn around the row per period (head = fract(uPhase) -> seamless); each
// dot lights as the head sweeps over its slot, with a comet-like falloff set by
// uChase. Wrapped distance keeps it continuous across the seam.
float pulseLit(int i, int count){
  float head = fract(uPhase) * float(count);          // 0..count head position
  float d = abs(float(i) + 0.5 - head);
  d = min(d, float(count) - d);                        // wrap around the row
  float sharp = mix(0.9, 2.4, clamp(uChase, 0.0, 1.5) / 1.5);
  return exp(-(d * d) * sharp);
}

// The whole row's emitted light at a fragment.
vec3 dotsLight(vec2 frag, float minDim){
  vec2 rel = (frag - uOrigin) / minDim;       // normalized, row-centred (y up)
  int count = dotCount();
  float radius = max(liveRadius(), 1e-3);

  // The breathe also gently modulates overall brightness (brighter on the inhale).
  float breatheB = 1.0 + sin(TAU * uPhase) * uBreathe * 0.5;
  float gain = uAmp * uExposure * breatheB;

  vec3 col = vec3(0.0);
  for (int i = 0; i < MAX_DOTS; i++) {
    if (i >= count) break;
    float cx = dotCenterX(i, count);
    vec2 dpos = rel - vec2(cx, 0.0);
    float dist = length(dpos);

    // Per-dot hue register: stops walk along the row (C0 -> C1 -> C2), so the row
    // reads as a coherent gradient rather than identical clones.
    float tcol = (count > 1) ? float(i) / float(count - 1) : 0.5;
    vec3 dotCol = paletteMix(clamp(tcol, 0.0, 1.0));

    // The pulse brightens whichever dot the head is sweeping over.
    float lit = pulseLit(i, count);
    float bright = 0.35 + 0.65 * lit;          // dim base, bright under the pulse

    // 1. CORE: a soft gaussian dot.
    float cov = exp(-(dist * dist) / (2.0 * radius * radius));
    col += dotCol * cov * gain * bright;

    // 2. GLOW: a wider, dim ambient halo under each dot.
    float gr = radius * 2.6;
    float glow = exp(-(dist * dist) / (2.0 * gr * gr));
    col += mix(dotCol, uC2, lit * 0.4) * glow * uGlow * gain * 0.3 * bright;
  }
  return col;
}

// ---------------------------------------------------------------------------
// SHADOW silhouette — the dots are small floating discs, so each casts a faint
// soft occlusion. Sample the row coverage at the offset shadow point and darken
// in proportion, kept subtle (small discs throw little shadow).
float dotsOcclusion(vec2 frag, float minDim){
  vec2 rel = (frag - uOrigin) / minDim;
  int count = dotCount();
  float radius = max(liveRadius(), 1e-3);
  float occ = 0.0;
  for (int i = 0; i < MAX_DOTS; i++) {
    if (i >= count) break;
    vec2 dpos = rel - vec2(dotCenterX(i, count), 0.0);
    float dist = length(dpos);
    occ = max(occ, exp(-(dist * dist) / (2.0 * radius * radius)));
  }
  return clamp(occ * uAmp, 0.0, 1.0);
}

vec4 dotsShadowColor(vec2 frag, float minDim){
  vec2 sp = frag - uShadowOffset;
  float soft = uShadowSoft;
  float occ = dotsOcclusion(sp, minDim);
  occ += dotsOcclusion(sp + vec2( soft, 0.0), minDim);
  occ += dotsOcclusion(sp + vec2(-soft, 0.0), minDim);
  occ += dotsOcclusion(sp + vec2(0.0,  soft), minDim);
  occ += dotsOcclusion(sp + vec2(0.0, -soft), minDim);
  occ /= 5.0;
  float dark = clamp(occ, 0.0, 1.0) * uShadowStrength * 0.5;
  vec3 tint = mix(vec3(1.0), 0.6 + 0.4 * normalize(uC0 + 1e-3), 0.2);
  vec3 mul = mix(vec3(1.0), tint, dark);
  return vec4(mul, 1.0);
}

void main(){
  vec2 frag = gl_FragCoord.xy;
  vec2 res = uResolution;
  float minDim = min(res.x, res.y);

  if (uShadow > 0.5) {
    fragColor = dotsShadowColor(frag, minDim);
    return;
  }

  vec3 col = dotsLight(frag, minDim);

  // ---- Tone + finishing ----
  col = tonemapACES(col * 0.95);

  // ---- Non-photoreal pass: cel / flat discs (whimsy). ----
  // Toward the cel end the soft gaussians become hard flat DISCS and the chase
  // snaps to a single posterized "lit" dot. The pass-runner already steps the
  // clock "on twos" (periodic — tempo.loop tiles the grid — so the loop seam
  // survives); here we flatten the tone.
  if (uStyle > 0.001) {
    vec2 rel = (frag - uOrigin) / minDim;
    int count = dotCount();
    float radius = max(liveRadius(), 1e-3);
    float breatheB = 1.0 + sin(TAU * uPhase) * uBreathe * 0.5;
    float gain = uAmp * uExposure * breatheB;
    vec3 cel = vec3(0.0);
    for (int i = 0; i < MAX_DOTS; i++) {
      if (i >= count) break;
      vec2 dpos = rel - vec2(dotCenterX(i, count), 0.0);
      float dist = length(dpos);
      float disc = 1.0 - smoothstep(radius * 0.85, radius, dist);   // hard flat disc
      float tcol = (count > 1) ? float(i) / float(count - 1) : 0.5;
      vec3 dotCol = clamp(paletteMix(clamp(tcol, 0.0, 1.0)) * 1.25, 0.0, 1.2);
      float lit = pulseLit(i, count);
      float litStep = step(0.6, lit);                                // one dot lit at a time
      cel += dotCol * disc * (0.4 + 0.6 * litStep)
           + mix(uC2, vec3(1.0), 0.5) * disc * litStep * 0.4;
    }
    cel *= gain;
    col = mix(col, cel, uStyle);
  }

  // Ordered dither (~1/255) to kill banding the screen blend reveals; faded out
  // toward the cel end where hard discs are intended. Seeded by the LOOP clock,
  // so even the dither field repeats exactly at the seam.
  col = ditherAdd(col, frag, uLoopS, 1.0 - uStyle);

  fragColor = dopLightOut(col);
}"""
