// @generated by @dopamine/build from effects/heartburst/heartburst.dope.json — do not edit.
//
// Heartburst as a Dopamine effect on the Android backbone — the DATA-DRIVEN
// registration shim. The ONLY hand-written Kotlin is the Canvas panel draw
// (HeartburstPanel.kt — panel geometry is code by design); everything else that
// isn't the GLSL lives in heartburst.dope.json — the mood→params mapping + palette
// (the loader), the per-frame logic (`tempo.frame`), `render.shadowHeightFrac`,
// `render.consts`, `render.config`, `tempo.reducedMotion`, any `tempo.loop`
// contract and the uniform `binding` contract. `dopePassPlan` + `dopePanelConfig`
// interpret that data through the generic panel runner. (The shader Kotlin is
// toolchain-generated from the same canonical web GLSL as the MSL.) The `.dope`
// bytes are the SAME as the web's (byte-parity proven by the 192-case grid).

package ai.dopamine.effect.heartburst

import ai.dopamine.core.DopeDoc
import ai.dopamine.core.DopeException
import ai.dopamine.core.DopePassPlan
import ai.dopamine.core.DopeResolveInput
import ai.dopamine.core.DopeValue
import ai.dopamine.core.EffectRegistry
import ai.dopamine.core.dopePassPlan
import ai.dopamine.core.parseDope
import ai.dopamine.core.resolveDopeParams
import ai.dopamine.gl.DrawableEffect
import ai.dopamine.gl.EffectContext
import ai.dopamine.gl.EffectInstance
import ai.dopamine.gl.PanelConfig
import ai.dopamine.gl.createPanelInstance
import ai.dopamine.gl.dopePanelConfig
import android.content.Context

class Heartburst(context: Context) : DrawableEffect {
    override val name: String = "heartburst"

    // Load the bundled `.dope` (the EXACT web bytes) from the merged APK assets —
    // proving the data spine is shared verbatim across platforms.
    val doc: DopeDoc = parseDope(
        context.assets.open("heartburst.dope.json").bufferedReader(Charsets.UTF_8).use { it.readText() },
    )

    // The whole factory (resolve consts/scatter, uniforms/bindings, the
    // per-frame logic, shadow height, reduced motion, the loop contract) is
    // data: heartburst.dope.json interpreted by the core backbone.
    private val plan: DopePassPlan = dopePassPlan(doc)
    private val scatterKey: String =
        plan.scatterKey ?: throw DopeException("dope: ${doc.id} has no binding.scatterKey")
    private val config: PanelConfig = dopePanelConfig(
        doc, HEARTBURST_VERTEX_SRC, HEARTBURST_FRAGMENT_SRC, plan,
        // The hand-written per-effect panel draw (the panel-draw seam:
        // effects/heartburst/android/HeartburstPanel.kt) — the ONLY per-effect
        // Kotlin; the backbone redraws + uploads it every frame.
        draw = ::drawHeartburstPanel,
    )

    override fun resolve(feeling: DopeResolveInput): Map<String, DopeValue> =
        resolveDopeParams(doc, feeling, consts = plan.consts, scatterKey = scatterKey)

    override fun create(params: Map<String, DopeValue>, ctx: EffectContext): EffectInstance =
        createPanelInstance(config, params, ctx)

    override val reducedMotionPeakMs: Double? = plan.reducedMotionPeakMs
    override val reducedMotionHoldMs: Double? = plan.reducedMotionHoldMs

    // The CONTINUOUS-loop contract (`tempo.loop`), null for one-shots: the
    // conductor re-arms a looping effect until the host stops the play handle.
    override val loop = doc.loop

    companion object {
        /** Construct + register the effect (needs a Context for the `.dope` asset). */
        fun register(context: Context): Heartburst {
            val fx = Heartburst(context.applicationContext)
            EffectRegistry.register(fx)
            return fx
        }
    }
}
