// @generated by @dopamine/build from effects/heartburst/heartburst.dope.json — do not edit.
//
// Heartburst as a Dopamine effect on the Swift backbone — the DATA-DRIVEN factory
// shell. The ONLY hand-written Swift is the Core Graphics panel draw
// (HeartburstPanel.swift — panel geometry is code by design); everything that isn't the
// shader lives in heartburst.dope.json — the mood→params mapping + OKLCH palette
// (the loader), the per-frame logic (`tempo.frame`), `render.shadowHeightFrac`,
// `render.consts`, `render.config`, any `tempo.loop` contract and the uniform
// `binding` contract. The generic `DopePanelPassConfig` interprets that data through
// the shared Metal pass runner. (The MSL is transpiled from the canonical web
// GLSL by the toolchain; `HeartburstUniforms` + `packHeartburstUniforms` are generated
// from the `.dope` binding contract.)

import Foundation
import DopamineCore

/// Heartburst: resolves a feeling → the flat `.dope` param bag. The drawable side
/// is Metal-only (below).
public final class Heartburst: EffectFactory {
    public let name = "heartburst"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("heartburst.dope", bundle: .module)
    }

    /// Resolve via the shared loader. The clamp consts and the scatter key come
    /// from the `.dope` itself (`render.consts` / `binding.scatterKey`) —
    /// byte-identical to the web.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling)
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal) && canImport(QuartzCore)
public extension Heartburst {
    /// The DATA-DRIVEN pass config: `tempo.frame`, `render.shadowHeightFrac`
    /// and `render.config` all come from the bundled `.dope`, evaluated by the
    /// shared backbone.
    static func passConfig() throws -> DopePanelPassConfig<HeartburstUniforms> {
        try DopePanelPassConfig(
            doc: DopeResource.loadDope("heartburst.dope", bundle: .module),
            vertexFunction: "heartburst_vertex",
            fragmentFunction: "heartburst_fragment",
            packUniforms: packHeartburstUniforms,
            // The hand-written per-effect panel draw (the panel-draw seam:
            // effects/heartburst/swift/HeartburstPanel.swift) — the ONLY per-effect
            // Swift; the backbone redraws + uploads it every frame.
            drawPanel: drawHeartburstPanel
        )
    }
}
#endif
