// @generated by @dopaminefx/build from effects/inkstroke/inkstroke.dope.json — do not edit.
//
// Inkstroke as a Dopamine effect on the Swift backbone — the DATA-DRIVEN factory
// shell. This effect ships NO hand-written Swift: everything that isn't the
// shader lives in inkstroke.dope.json — the mood→params mapping + OKLCH palette
// (the loader), the per-frame logic (`tempo.frame`), `render.shadowHeightFrac`,
// `render.consts`, `render.config`, any `tempo.loop` contract and the uniform
// `binding` contract. The generic `DopePassConfig` interprets that data through
// the shared Metal pass runner. (The MSL is transpiled from the canonical web
// GLSL by the toolchain; `InkstrokeUniforms` + `packInkstrokeUniforms` are generated
// from the `.dope` binding contract.)

import Foundation
import DopamineCore

/// Inkstroke: resolves a feeling → the flat `.dope` param bag. The drawable side
/// is Metal-only (below).
public final class Inkstroke: EffectFactory {
    public let name = "inkstroke"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("inkstroke.dope", bundle: .module)
    }

    /// Resolve via the shared loader. The clamp consts and the scatter key come
    /// from the `.dope` itself (`render.consts` / `binding.scatterKey`) —
    /// byte-identical to the web.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling)
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)
public extension Inkstroke {
    /// The DATA-DRIVEN pass config: `tempo.frame`, `render.shadowHeightFrac`
    /// and `render.config` all come from the bundled `.dope`, evaluated by the
    /// shared backbone.
    static func passConfig() throws -> DopePassConfig<InkstrokeUniforms> {
        try DopePassConfig(
            doc: DopeResource.loadDope("inkstroke.dope", bundle: .module),
            vertexFunction: "inkstroke_vertex",
            fragmentFunction: "inkstroke_fragment",
            packUniforms: packInkstrokeUniforms
        )
    }
}
#endif
