// @generated by @dopaminefx/build from effects/lightning/lightning.dope.json — do not edit.
//
// Lightning as a Dopamine effect on the Swift backbone — the DATA-DRIVEN factory
// shell. This effect ships NO hand-written Swift: everything that isn't the
// shader lives in lightning.dope.json — the mood→params mapping + OKLCH palette
// (the loader), the per-frame logic (`tempo.frame`), `render.shadowHeightFrac`,
// `render.consts`, `render.config`, any `tempo.loop` contract and the uniform
// `binding` contract. The generic `DopePassConfig` interprets that data through
// the shared Metal pass runner. (The MSL is transpiled from the canonical web
// GLSL by the toolchain; `LightningUniforms` + `packLightningUniforms` are generated
// from the `.dope` binding contract.)

import Foundation
import DopamineCore

/// Lightning: resolves a feeling → the flat `.dope` param bag. The drawable side
/// is Metal-only (below).
public final class Lightning: EffectFactory {
    public let name = "lightning"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("lightning.dope", bundle: .module)
    }

    /// Resolve via the shared loader. The clamp consts and the scatter key come
    /// from the `.dope` itself (`render.consts` / `binding.scatterKey`) —
    /// byte-identical to the web.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling)
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)
public extension Lightning {
    /// The DATA-DRIVEN pass config: `tempo.frame`, `render.shadowHeightFrac`
    /// and `render.config` all come from the bundled `.dope`, evaluated by the
    /// shared backbone.
    static func passConfig() throws -> DopePassConfig<LightningUniforms> {
        try DopePassConfig(
            doc: DopeResource.loadDope("lightning.dope", bundle: .module),
            vertexFunction: "lightning_vertex",
            fragmentFunction: "lightning_fragment",
            packUniforms: packLightningUniforms,
            frameArrays: { info, params, width, height, origin in
                // The generated LightningRenderer (transpiled from the single web
                // logic module) precomputes the frame geometry; `binding.arrays`
                // maps its bundle onto the fragment buffers.
                func num(_ k: String) -> Double { if case let .number(v)? = params[k] { return v }; return 0 }
                let out = computeLightningArrays(
                    style: num("style"),
                    thickness: num("thickness"),
                    jagged: num("jagged"),
                    branches: num("branches"),
                    boltSeed: num("boltSeed"),
                    width: Double(width),
                    height: Double(height),
                    originX: Double(origin.x),
                    originY: Double(origin.y),
                    elapsedMs: info.animMs,
                    life: info.life
                )
                return [
                    PassFrameArray(bufferIndex: 1, data: out.verts),
                    PassFrameArray(bufferIndex: 2, data: out.meta)
                ]
            }
        )
    }
}
#endif
