// @generated by @dopaminefx/build from effects/solarbloom/solarbloom.dope.json — do not edit.
//
// Solarbloom as a Dopamine effect on the Android backbone — the DATA-DRIVEN
// registration shim. The ONLY hand-written Kotlin is the Canvas SPRITE-PANEL
// draw (SolarbloomPanel.kt — a PASS hybrid whose panel binds at its render.panel
// unit ALONGSIDE the baked-SDF aux; panel geometry is code by design); else
// isn't the GLSL lives in solarbloom.dope.json — the mood→params mapping + palette
// (the loader), the per-frame logic (`tempo.frame`), `render.shadowHeightFrac`,
// `render.consts`, `render.config`, `tempo.reducedMotion`, any `tempo.loop`
// contract and the uniform `binding` contract. `dopePassPlan` + `dopePassConfig`
// interpret that data through the generic pass runner. (The shader Kotlin is
// toolchain-generated from the same canonical web GLSL as the MSL.) The `.dope`
// bytes are the SAME as the web's (byte-parity proven by the 192-case grid).

package ai.dopamine.effect.solarbloom

import ai.dopamine.core.DopeDoc
import ai.dopamine.core.DopeException
import ai.dopamine.core.DopePassPlan
import ai.dopamine.core.DopeResolveInput
import ai.dopamine.core.DopeValue
import ai.dopamine.core.EffectRegistry
import ai.dopamine.core.dopePassPlan
import ai.dopamine.core.parseDope
import ai.dopamine.core.resolveDopeParams
import ai.dopamine.gl.DrawableEffect
import ai.dopamine.gl.EffectContext
import ai.dopamine.gl.EffectInstance
import ai.dopamine.gl.PassConfig
import ai.dopamine.gl.createPassInstance
import ai.dopamine.gl.dopePassConfig
import android.content.Context

class Solarbloom(context: Context) : DrawableEffect {
    override val name: String = "solarbloom"

    // Load the bundled `.dope` (the EXACT web bytes) from the merged APK assets —
    // proving the data spine is shared verbatim across platforms.
    val doc: DopeDoc = parseDope(
        context.assets.open("solarbloom.dope.json").bufferedReader(Charsets.UTF_8).use { it.readText() },
    )

    // The whole factory (resolve consts/scatter, uniforms/bindings, the
    // per-frame logic, shadow height, reduced motion, the loop contract) is
    // data: solarbloom.dope.json interpreted by the core backbone.
    private val plan: DopePassPlan = dopePassPlan(doc)
    private val scatterKey: String =
        plan.scatterKey ?: throw DopeException("dope: ${doc.id} has no binding.scatterKey")
    private val config: PassConfig = dopePassConfig(
        doc, SOLARBLOOM_VERTEX_SRC, SOLARBLOOM_FRAGMENT_SRC, plan,
        // The hand-written per-effect SPRITE-PANEL draw (the panel-draw seam:
        // effects/solarbloom/android/SolarbloomPanel.kt) — the ONLY per-effect Kotlin;
        // a PASS hybrid whose panel binds at its render.panel unit ALONGSIDE the
        // baked-SDF aux. The backbone redraws + uploads it every frame.
        draw = ::drawSolarbloomPanel,
    )

    override fun resolve(feeling: DopeResolveInput): Map<String, DopeValue> =
        resolveDopeParams(doc, feeling, consts = plan.consts, scatterKey = scatterKey)

    override fun create(params: Map<String, DopeValue>, ctx: EffectContext): EffectInstance =
        createPassInstance(config, params, ctx)

    override val reducedMotionPeakMs: Double? = plan.reducedMotionPeakMs
    override val reducedMotionHoldMs: Double? = plan.reducedMotionHoldMs

    // The CONTINUOUS-loop contract (`tempo.loop`), null for one-shots: the
    // conductor re-arms a looping effect until the host stops the play handle.
    override val loop = doc.loop

    companion object {
        /** Construct + register the effect (needs a Context for the `.dope` asset). */
        fun register(context: Context): Solarbloom {
            val fx = Solarbloom(context.applicationContext)
            EffectRegistry.register(fx)
            return fx
        }
    }
}
