// @generated by @dopamine/build from effects/lightning — do not edit.
//
// PURE-JVM numeric parity gate for the GENERATED LightningRenderer.kt: replays the
// committed fixture grid (dumped from the web lightning-logic.ts — ground truth)
// and asserts every float of every precomputed array matches the web output.
// Lives in dopamine-core's testGenerated source set (synced by `dopamine build`)
// so the plain-JVM CI job compiles the generated Kotlin with NO Android SDK.

package ai.dopamine.effect.lightning

import ai.dopamine.core.JsonValue
import ai.dopamine.core.parseOrderedJson
import kotlin.math.abs
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class LightningLogicParityTest {

    private fun resource(name: String): String {
        val stream = javaClass.classLoader.getResourceAsStream(name)
            ?: error("missing test resource: $name")
        return stream.bufferedReader(Charsets.UTF_8).use { it.readText() }
    }

    /** Doubles end-to-end; only libm transcendentals may differ by ULPs across
     *  platforms, far below the float32 quantum the arrays store. */
    private fun checkArray(label: String, expected: List<JsonValue>, got: FloatArray) {
        assertEquals("$label size", expected.size, got.size)
        for (i in expected.indices) {
            val e = expected[i].asNumber!!
            val g = got[i].toDouble()
            assertEquals("$label[$i]", e, g, maxOf(1e-6, abs(e) * 1e-6))
        }
    }

    @Test
    fun logicParityAcrossGrid() {
        val fixture = parseOrderedJson(resource("lightning-logic-parity.json"))
        val cases = fixture["cases"]?.asArray ?: error("fixture missing cases")
        assertTrue("expected a non-empty grid", cases.isNotEmpty())
        for ((caseIdx, c) in cases.withIndex()) {
            val out = computeLightningArrays(
                style = c["style"]!!.asNumber!!,
                thickness = c["thickness"]!!.asNumber!!,
                jagged = c["jagged"]!!.asNumber!!,
                branches = c["branches"]!!.asNumber!!,
                boltSeed = c["boltSeed"]!!.asNumber!!,
                width = c["width"]!!.asNumber!!,
                height = c["height"]!!.asNumber!!,
                originX = c["originX"]!!.asNumber!!,
                originY = c["originY"]!!.asNumber!!,
                elapsedMs = c["elapsedMs"]!!.asNumber!!,
                life = c["life"]!!.asNumber!!,
            )
            checkArray("verts[$caseIdx]", c["verts"]!!.asArray!!, out.verts)
            checkArray("meta[$caseIdx]", c["meta"]!!.asArray!!, out.meta)
        }
    }
}
