// @generated by @dopaminefx/build from effects/lightning/web/src/lightning-logic.ts — do not edit.
//
// Lightning's CPU-precomputed per-frame geometry, TRANSPILED from the single web
// source by tools/dopamine/src/logic.mjs (the x-build.logic block). Numeric
// semantics mirror JS: doubles end-to-end, float32 narrowing only at the
// array writes, identical operation order. Gated byte-for-byte by
// tools/dopamine/test/logic.test.mjs and numerically by the committed
// web-dumped parity fixture (pure-JVM JUnit + XCTest replays).

package ai.dopamine.effect.lightning

import kotlin.math.PI
import kotlin.math.floor
import kotlin.math.hypot
import kotlin.math.pow
import kotlin.math.sin

const val MAX_FORKS = 7
const val BOLT_SEGS = 14
const val MAX_BOLTS = MAX_FORKS + 1
const val VERTS_PER_BOLT = BOLT_SEGS + 1
const val STRIKE_MS = 130

private class Vec2(val x: Double, val y: Double)

/** The precomputed frame arrays the shader consumes (verts / meta). */
class LightningArrays(val verts: FloatArray, val meta: FloatArray)

private fun clamp(x: Double, lo: Double, hi: Double): Double {
    return (if (x < lo) lo else (if (x > hi) hi else x))
}

private fun clamp01(x: Double): Double {
    return (if (x < 0.0) 0.0 else (if (x > 1.0) 1.0 else x))
}

private fun smoothstep(e0: Double, e1: Double, x: Double): Double {
    val t = clamp01((x - e0) / (e1 - e0))
    return t * t * (3.0 - 2.0 * t)
}

private fun fract(x: Double): Double {
    return x - floor(x)
}

private fun mix(a: Double, b: Double, t: Double): Double {
    return a + (b - a) * t
}

fun strikeProgress(elapsedMs: Double): Double {
    val x = clamp01(elapsedMs / STRIKE_MS.toDouble())
    return 1.0 - (1.0 - x).pow(5.0)
}

private fun hash11(p0: Double): Double {
    var p = p0
    p = fract(p * 0.1031)
    p *= p + 33.33
    p *= p + p
    return fract(p)
}

private fun hash21x(p: Double): Double {
    var x = fract(p * 0.1031)
    var y = fract(p * 0.103)
    var z = fract(p * 0.0973)
    val d = x * (y + 33.33) + y * (z + 33.33) + z * (x + 33.33)
    x += d
    y += d
    z += d
    return fract((x + y) * z)
}

private fun hash21(p: Double): Vec2 {
    var x = fract(p * 0.1031)
    var y = fract(p * 0.103)
    var z = fract(p * 0.0973)
    val d = x * (y + 33.33) + y * (z + 33.33) + z * (x + 33.33)
    x += d
    y += d
    z += d
    return Vec2(fract((x + y) * z), fract((x + z) * y))
}

private fun vnoise(x: Double, y: Double): Double {
    val ix = floor(x)
    val iy = floor(y)
    val fx = x - ix
    val fy = y - iy
    val ux = fx * fx * (3.0 - 2.0 * fx)
    val uy = fy * fy * (3.0 - 2.0 * fy)
    val a = hash11(ix * 1.0 + iy * 57.0)
    val b = hash11((ix + 1.0) * 1.0 + iy * 57.0)
    val c = hash11(ix * 1.0 + (iy + 1.0) * 57.0)
    val d = hash11((ix + 1.0) * 1.0 + (iy + 1.0) * 57.0)
    return mix(mix(a, b, ux), mix(c, d, ux), uy)
}

private fun fbm(x0: Double, y0: Double): Double {
    var x = x0
    var y = y0
    var s = 0.0
    var a = 0.5
    for (i in 0 until 4) {
        s += a * vnoise(x, y)
        val nx = (0.8 * x + 0.6 * y) * 2.03
        val ny = (-0.6 * x + 0.8 * y) * 2.03
        x = nx
        y = ny
        a *= 0.5
    }
    return s
}

private fun boltPoint(A: Vec2, B: Vec2, t: Double, seedOff: Double, seed: Double, jagged: Double, beat: Double): Vec2 {
    val dx = B.x - A.x
    val dy = B.y - A.y
    val len = maxOf(hypot(dx, dy), 1.0)
    val dirx = dx / len
    val diry = dy / len
    val nrmx = -diry
    val nrmy = dirx
    val n = fbm(t * 6.0 + seedOff + seed, beat * 0.5) - 0.5
    val fine = fbm(t * 22.0 + seedOff * 3.1 + seed, beat) - 0.5
    val taper = sin(t * PI)
    val off = (n * 1.6 + fine * 0.5) * jagged * len * 0.16 * taper
    return Vec2(A.x + dirx * (t * len) + nrmx * off, A.y + diry * (t * len) + nrmy * off)
}

private fun writeBolt(verts: FloatArray, b: Double, A: Vec2, B: Vec2, drawn: Double, seedOff: Double, seed: Double, jagged: Double, beat: Double): Double {
    val base = b * VERTS_PER_BOLT.toDouble()
    var last = 0
    val v0 = boltPoint(A, B, 0.0, seedOff, seed, jagged, beat)
    verts[((base + 0.0) * 2.0).toInt()] = v0.x.toFloat()
    verts[((base + 0.0) * 2.0 + 1.0).toInt()] = v0.y.toFloat()
    for (i in 1 .. BOLT_SEGS) {
        val t = i.toDouble() / BOLT_SEGS.toDouble()
        if (t - 1.0 / BOLT_SEGS.toDouble() > drawn) {
            break
        }
        val tc = minOf(t, drawn)
        val v = boltPoint(A, B, tc, seedOff, seed, jagged, beat)
        verts[((base + i.toDouble()) * 2.0).toInt()] = v.x.toFloat()
        verts[((base + i.toDouble()) * 2.0 + 1.0).toInt()] = v.y.toFloat()
        last = i
    }
    return last.toDouble()
}

fun computeLightningArrays(style: Double, thickness: Double, jagged: Double, branches: Double, boltSeed: Double, width: Double, height: Double, originX: Double, originY: Double, elapsedMs: Double, life: Double): LightningArrays {
    val verts = FloatArray(MAX_BOLTS * VERTS_PER_BOLT * 2)
    val meta = FloatArray(MAX_BOLTS * 4)
    val strike = strikeProgress(elapsedMs)
    if (strike <= 0.0) {
        return LightningArrays(verts, meta)
    }
    val seed = boltSeed
    val beat = floor((elapsedMs / 1000.0) * 12.0) * style
    val jx = (hash21x(seed * 1.7) - 0.5) * width * 0.5
    val A = Vec2(clamp(originX + jx, width * 0.12, width * 0.88), height * 1.02)
    val B = Vec2(originX, originY)
    val mainSegs = writeBolt(verts, 0.0, A, B, strike, 0.0, seed, jagged, beat)
    meta[0] = mainSegs.toFloat()
    meta[1] = thickness.toFloat()
    meta[2] = 1.0f
    meta[3] = 1.0f
    val forks = maxOf(0.0, minOf(MAX_FORKS.toDouble(), floor(branches + 0.5)))
    val dlenRaw = hypot(B.x - A.x, B.y - A.y)
    val dlen = (if (dlenRaw == 0.0) 1.0 else dlenRaw)
    val dirx = (B.x - A.x) / dlen
    val diry = (B.y - A.y) / dlen
    val nrmx = -diry
    val nrmy = dirx
    val forkFade = 0.6 + 0.4 * (1.0 - smoothstep(0.5, 1.0, life))
    for (i in 0 until forks.toInt()) {
        val b = 1 + i
        val hh = hash21(i.toDouble() * 9.7 + seed + 3.0)
        val launchT = 0.18 + hh.x * 0.62
        if (strike < launchT) {
            meta[b * 4] = 0.0f
            continue
        }
        val forkA = boltPoint(A, B, launchT, 0.0, seed, jagged, beat)
        val ang = (hh.y - 0.5) * 2.2
        val reach = (0.18 + hh.x * 0.22) * dlen
        val ex = dirx * (0.5 + hh.y) + nrmx * ang
        val ey = diry * (0.5 + hh.y) + nrmy * ang
        val forkB = Vec2(forkA.x + ex * reach, forkA.y + ey * reach)
        val forkDrawn = clamp((strike - launchT) / maxOf(1.0 - launchT, 0.05), 0.0, 1.0)
        val segs = writeBolt(verts, b.toDouble(), forkA, forkB, forkDrawn, (i * 17 + 5).toDouble(), seed, jagged, beat)
        meta[b * 4] = segs.toFloat()
        meta[b * 4 + 1] = (thickness * 0.6).toFloat()
        meta[b * 4 + 2] = forkFade.toFloat()
        meta[b * 4 + 3] = 0.0f
    }
    return LightningArrays(verts, meta)
}
