// @generated by @dopamine/build from effects/lightning — do not edit.
//
// Numeric parity gate for the GENERATED LightningRenderer.swift: replays the
// committed fixture grid (dumped from the web lightning-logic.ts — ground truth)
// and asserts every float of every precomputed array. The generated renderer is
// PURE Swift (no Metal), so this runs on Linux too: `swift test` in the package.

import XCTest
import Foundation
import DopamineEffectLightning

final class LightningLogicParityTests: XCTestCase {

    /// Doubles end-to-end; only libm transcendentals may differ by ULPs across
    /// platforms, far below the float32 quantum the arrays store.
    private func check(_ label: String, _ expected: [NSNumber], _ got: [Float]) {
        XCTAssertEqual(expected.count, got.count, "\(label) size")
        for (i, e) in expected.enumerated() {
            let want = e.doubleValue
            let have = Double(got[i])
            XCTAssertEqual(want, have, accuracy: max(1e-6, abs(want) * 1e-6), "\(label)[\(i)]")
        }
    }

    func testLogicParityAcrossGrid() throws {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "lightning-logic-parity", withExtension: "json"))
        let data = try Data(contentsOf: url)
        let root = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
        let cases = try XCTUnwrap(root["cases"] as? [[String: Any]])
        XCTAssertFalse(cases.isEmpty, "expected a non-empty grid")
        for (caseIdx, c) in cases.enumerated() {
            func num(_ key: String) -> Double { (c[key] as! NSNumber).doubleValue }
            let out = computeLightningArrays(style: num("style"), thickness: num("thickness"), jagged: num("jagged"), branches: num("branches"), boltSeed: num("boltSeed"), width: num("width"), height: num("height"), originX: num("originX"), originY: num("originY"), elapsedMs: num("elapsedMs"), life: num("life"))
            check("verts[\(caseIdx)]", c["verts"] as! [NSNumber], out.verts)
            check("meta[\(caseIdx)]", c["meta"] as! [NSNumber], out.meta)
        }
    }
}
