// @generated by @dopaminefx/build from effects/lightning/web/src/lightning-logic.ts — do not edit.
//
// Lightning's CPU-precomputed per-frame geometry, TRANSPILED from the single web
// source by tools/dopamine/src/logic.mjs (the x-build.logic block). Numeric
// semantics mirror JS: doubles end-to-end, float32 narrowing only at the
// array writes, identical operation order. Gated byte-for-byte by
// tools/dopamine/test/logic.test.mjs and numerically by the committed
// web-dumped parity fixture (pure-JVM JUnit + XCTest replays).

import Foundation

public let MAX_FORKS = 7
public let BOLT_SEGS = 14
public let MAX_BOLTS = MAX_FORKS + 1
public let VERTS_PER_BOLT = BOLT_SEGS + 1
public let STRIKE_MS = 130

private struct Vec2 { var x: Double; var y: Double }

private func clamp(_ x: Double, _ lo: Double, _ hi: Double) -> Double {
    return (x < lo ? lo : (x > hi ? hi : x))
}

private func clamp01(_ x: Double) -> Double {
    return (x < 0.0 ? 0.0 : (x > 1.0 ? 1.0 : x))
}

private func smoothstep(_ e0: Double, _ e1: Double, _ x: Double) -> Double {
    let t = clamp01((x - e0) / (e1 - e0))
    return t * t * (3.0 - 2.0 * t)
}

private func fract(_ x: Double) -> Double {
    return x - floor(x)
}

private func mix(_ a: Double, _ b: Double, _ t: Double) -> Double {
    return a + (b - a) * t
}

public func strikeProgress(elapsedMs: Double) -> Double {
    let x = clamp01(elapsedMs / Double(STRIKE_MS))
    return 1.0 - pow(1.0 - x, 5.0)
}

private func hash11(_ p0: Double) -> Double {
    var p = p0
    p = fract(p * 0.1031)
    p *= p + 33.33
    p *= p + p
    return fract(p)
}

private func hash21x(_ p: Double) -> Double {
    var x = fract(p * 0.1031)
    var y = fract(p * 0.103)
    var z = fract(p * 0.0973)
    let d = x * (y + 33.33) + y * (z + 33.33) + z * (x + 33.33)
    x += d
    y += d
    z += d
    return fract((x + y) * z)
}

private func hash21(_ p: Double) -> Vec2 {
    var x = fract(p * 0.1031)
    var y = fract(p * 0.103)
    var z = fract(p * 0.0973)
    let d = x * (y + 33.33) + y * (z + 33.33) + z * (x + 33.33)
    x += d
    y += d
    z += d
    return Vec2(x: fract((x + y) * z), y: fract((x + z) * y))
}

private func vnoise(_ x: Double, _ y: Double) -> Double {
    let ix = floor(x)
    let iy = floor(y)
    let fx = x - ix
    let fy = y - iy
    let ux = fx * fx * (3.0 - 2.0 * fx)
    let uy = fy * fy * (3.0 - 2.0 * fy)
    let a = hash11(ix * 1.0 + iy * 57.0)
    let b = hash11((ix + 1.0) * 1.0 + iy * 57.0)
    let c = hash11(ix * 1.0 + (iy + 1.0) * 57.0)
    let d = hash11((ix + 1.0) * 1.0 + (iy + 1.0) * 57.0)
    return mix(mix(a, b, ux), mix(c, d, ux), uy)
}

private func fbm(_ x0: Double, _ y0: Double) -> Double {
    var x = x0
    var y = y0
    var s = 0.0
    var a = 0.5
    for _ in 0 ..< 4 {
        s += a * vnoise(x, y)
        let nx = (0.8 * x + 0.6 * y) * 2.03
        let ny = (-0.6 * x + 0.8 * y) * 2.03
        x = nx
        y = ny
        a *= 0.5
    }
    return s
}

private func boltPoint(_ A: Vec2, _ B: Vec2, _ t: Double, _ seedOff: Double, _ seed: Double, _ jagged: Double, _ beat: Double) -> Vec2 {
    let dx = B.x - A.x
    let dy = B.y - A.y
    let len = max(hypot(dx, dy), 1.0)
    let dirx = dx / len
    let diry = dy / len
    let nrmx = -diry
    let nrmy = dirx
    let n = fbm(t * 6.0 + seedOff + seed, beat * 0.5) - 0.5
    let fine = fbm(t * 22.0 + seedOff * 3.1 + seed, beat) - 0.5
    let taper = sin(t * Double.pi)
    let off = (n * 1.6 + fine * 0.5) * jagged * len * 0.16 * taper
    return Vec2(x: A.x + dirx * (t * len) + nrmx * off, y: A.y + diry * (t * len) + nrmy * off)
}

private func writeBolt(_ verts: inout [Float], _ b: Double, _ A: Vec2, _ B: Vec2, _ drawn: Double, _ seedOff: Double, _ seed: Double, _ jagged: Double, _ beat: Double) -> Double {
    let base = b * Double(VERTS_PER_BOLT)
    var last = 0
    let v0 = boltPoint(A, B, 0.0, seedOff, seed, jagged, beat)
    verts[Int((base + 0.0) * 2.0)] = Float(v0.x)
    verts[Int((base + 0.0) * 2.0 + 1.0)] = Float(v0.y)
    for i in 1 ... BOLT_SEGS {
        let t = Double(i) / Double(BOLT_SEGS)
        if (t - 1.0 / Double(BOLT_SEGS) > drawn) {
            break
        }
        let tc = min(t, drawn)
        let v = boltPoint(A, B, tc, seedOff, seed, jagged, beat)
        verts[Int((base + Double(i)) * 2.0)] = Float(v.x)
        verts[Int((base + Double(i)) * 2.0 + 1.0)] = Float(v.y)
        last = i
    }
    return Double(last)
}

public func computeLightningArrays(style: Double, thickness: Double, jagged: Double, branches: Double, boltSeed: Double, width: Double, height: Double, originX: Double, originY: Double, elapsedMs: Double, life: Double) -> (verts: [Float], meta: [Float]) {
    var verts = [Float](repeating: 0, count: MAX_BOLTS * VERTS_PER_BOLT * 2)
    var meta = [Float](repeating: 0, count: MAX_BOLTS * 4)
    let strike = strikeProgress(elapsedMs: elapsedMs)
    if (strike <= 0.0) {
        return (verts: verts, meta: meta)
    }
    let seed = boltSeed
    let beat = floor((elapsedMs / 1000.0) * 12.0) * style
    let jx = (hash21x(seed * 1.7) - 0.5) * width * 0.5
    let A = Vec2(x: clamp(originX + jx, width * 0.12, width * 0.88), y: height * 1.02)
    let B = Vec2(x: originX, y: originY)
    let mainSegs = writeBolt(&verts, 0.0, A, B, strike, 0.0, seed, jagged, beat)
    meta[0] = Float(mainSegs)
    meta[1] = Float(thickness)
    meta[2] = 1.0
    meta[3] = 1.0
    let forks = max(0.0, min(Double(MAX_FORKS), floor(branches + 0.5)))
    let dlenRaw = hypot(B.x - A.x, B.y - A.y)
    let dlen = (dlenRaw == 0.0 ? 1.0 : dlenRaw)
    let dirx = (B.x - A.x) / dlen
    let diry = (B.y - A.y) / dlen
    let nrmx = -diry
    let nrmy = dirx
    let forkFade = 0.6 + 0.4 * (1.0 - smoothstep(0.5, 1.0, life))
    for i in 0 ..< Int(forks) {
        let b = 1 + i
        let hh = hash21(Double(i) * 9.7 + seed + 3.0)
        let launchT = 0.18 + hh.x * 0.62
        if (strike < launchT) {
            meta[b * 4] = 0.0
            continue
        }
        let forkA = boltPoint(A, B, launchT, 0.0, seed, jagged, beat)
        let ang = (hh.y - 0.5) * 2.2
        let reach = (0.18 + hh.x * 0.22) * dlen
        let ex = dirx * (0.5 + hh.y) + nrmx * ang
        let ey = diry * (0.5 + hh.y) + nrmy * ang
        let forkB = Vec2(x: forkA.x + ex * reach, y: forkA.y + ey * reach)
        let forkDrawn = clamp((strike - launchT) / max(1.0 - launchT, 0.05), 0.0, 1.0)
        let segs = writeBolt(&verts, Double(b), forkA, forkB, forkDrawn, Double(i * 17 + 5), seed, jagged, beat)
        meta[b * 4] = Float(segs)
        meta[b * 4 + 1] = Float(thickness * 0.6)
        meta[b * 4 + 2] = Float(forkFade)
        meta[b * 4 + 3] = 0.0
    }
    return (verts: verts, meta: meta)
}
