// Halo as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-halo/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + a tiny config naming its scalar params and packing them
// into the uniform struct + the per-frame breathe gate}. Everything else — the
// `.dope` mapping, the OKLCH palette, the registry, the two-pass loop, the
// standard uniforms, the shadow geometry — is shared DopamineCore. The
// numeric/palette bag comes verbatim from the bundled `.dope` (the SAME bytes as
// the web).
//
// CONTINUOUS / LOOPING. Halo is Dopamine's first continuous effect. The other
// nine are one-shot reward moments gated by the held-breath `envelope(life)` (a
// 0→peak→0 fade that would not loop). Halo instead drives all motion off PERIODIC
// functions of `uTimeS` in the shader and returns a STEADY periodic `amp` from
// `frame()` (see `haloBreathe`), so it LOOPS SEAMLESSLY: the `.dope` sets `period
// = 1.5 s` and `durationMs = 6000` (= 4 periods), and 1.5 s is exactly 18
// "animate-on-twos" steps, so the frame at `t == durationMs` matches `t == 0` at
// every whimsy.

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// Halo's loop period in seconds. The shader drives every periodic function off
/// this, and the `.dope` makes `durationMs` an integer multiple of it (also a
/// `render.params` uniform `uPeriod`, resolved from the `.dope` const). Mirrored
/// here for the breathe gate so the Swift frame() matches the web exactly.
public let HALO_DEFAULT_PERIOD_S: Double = 1.5

/// Halo's STEADY breathe gate at elapsed seconds `timeS` for loop period
/// `periodS`: a slow sine swinging ~0.7..1.0, periodic in `timeS` (NOT a
/// life-based fade), so the loop is seamless. `haloBreathe(0) == 0.85` and
/// `haloBreathe(N·periodS) == haloBreathe(0)`. Mirror of the web `haloBreathe`
/// (halo-tempo.ts) + the Android `haloBreathe` (HaloTempo.kt).
public func haloBreathe(_ timeS: Double, period periodS: Double) -> Double {
    let ph = (2.0 * Double.pi * timeS) / max(periodS, 1e-3)
    return 0.85 + 0.15 * sin(ph)
}

/// Halo: resolves a feeling → the flat `.dope` param bag. The drawable side is
/// Metal-only (below).
public final class Halo: EffectFactory {
    public let name = "halo"
    public let doc: DopeDoc

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("halo.dope", bundle: .module)
    }

    /// Resolve via the shared loader. Halo references no clamp consts; `haloSeed`
    /// is the scatter key — both byte-identical to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: [:], scatterKey: "haloSeed")
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `HaloUniforms` + `packHaloUniforms(...)` are GENERATED by
// scripts/gen-uniforms.mjs into `HaloUniforms.swift` (the SAME source that emits
// the MSL `struct HaloUniforms`), so the Swift struct and the `.metal` struct
// cannot drift. The config below just supplies the standard half + the frame()
// breathe gate and calls the generated packer.

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height (= the ring's outer reach), the per-frame STEADY
/// breathe gate (NOT an envelope), and the uniform packer that lays the resolved
/// bag into the struct.
public struct HaloConfig: PassConfig {
    public typealias Uniforms = HaloUniforms
    public var vertexFunction = "halo_vertex"
    public var fragmentFunction = "halo_fragment"
    public var usesOrigin = true
    public init() {}

    /// A thin floating loop throws a small shadow; key its occluder "height" to
    /// the ring's outer reach (radius + a little width).
    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        var ringRadius = 0.0, ringWidth = 0.0
        if case let .number(v)? = params["ringRadius"] { ringRadius = v }
        if case let .number(v)? = params["ringWidth"] { ringWidth = v }
        return min(ringRadius + ringWidth * 2, 1)
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        // CONTINUOUS: a STEADY periodic breathe gate driven off elapsed seconds —
        // NOT `envelope(life)`. `animMs/1000` is the seconds clock the shader also
        // reads as `uTimeS`; haloBreathe is periodic with `period`, so the loop seam
        // is exact. `period` is a resolved `.dope` param (the const 1.5).
        var period = HALO_DEFAULT_PERIOD_S
        if case let .number(v)? = params["period"] { period = v }
        let amp = haloBreathe(info.animMs / 1000, period: period)
        // Halo has no per-frame extras (no glyph / texture plumbing); the breathe
        // amp gates global brightness + the shadow geometry.
        return (amp, [:])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packHaloUniforms`). The standard half + named scalars come from the
    /// generated code; Halo has no host-side extras to top up, so the extras map
    /// passes straight through.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> HaloUniforms {
        return packHaloUniforms(standard: s, params: params, extras: extras)
    }
}
#endif
