// Solarbloom as a Dopamine effect on the Swift backbone — mirror of the web
// `effect-solarbloom/src/index.ts`.
//
// Per the generalization mandate, the ONLY per-effect code here is {the MSL
// shader (in Shaders/) + the bespoke tempo (SolarbloomTempo.swift) + a tiny
// config naming its scalar params and packing them into the uniform struct}.
// Everything else — the `.dope` mapping, the OKLCH palette, the registry, the
// two-pass loop, the standard uniforms, the shadow geometry — is shared
// DopamineCore. The numeric/palette bag comes verbatim from the bundled `.dope`
// (the SAME bytes as the web); the whimsy-picked check glyph is composed on top
// with the shared `pickBand` (no rng, no effect on parity).

import Foundation
import DopamineCore

#if canImport(Metal)
import simd
#endif

/// The single source of truth for the mote cap: BOTH the MSL `#define MAX_MOTES`
/// and the integer-clamp const the `.dope` references (`clampMax: "MAX_MOTES"`).
public let MAX_MOTES: Double = 80

/// A concrete check-glyph choice (bundled face + the codepoint to render).
public struct CheckGlyph: Equatable {
    public var family: String
    public var char: String
}

/// Solarbloom: resolves a feeling → the flat `.dope` param bag (+ the picked
/// check glyph). The drawable side is Metal-only (below).
public final class Solarbloom: EffectFactory {
    public let name = "solarbloom"
    public let doc: DopeDoc
    private let glyphBands: [CheckGlyph]

    public init() throws {
        // Load the bundled `.dope` (the EXACT web bytes) from this package's
        // resource bundle — proving the data spine is shared verbatim.
        self.doc = try DopeResource.loadDope("solarbloom.dope", bundle: .module)
        // The whimsy→check-glyph fallback BANDS live in the .dope content section.
        var bands: [CheckGlyph] = []
        if let arr = doc.raw["content"]?["glyphBands"]?.asArray {
            for b in arr {
                if let fam = b["family"]?.asString, let ch = b["char"]?.asString {
                    bands.append(CheckGlyph(family: fam, char: ch))
                }
            }
        }
        self.glyphBands = bands.isEmpty
            ? [CheckGlyph(family: "Dopamine Check Symbols", char: "\u{2713}")]
            : bands
    }

    /// Resolve via the shared loader. `MAX_MOTES` is the only const; `moteSeed`
    /// is the scatter key — both byte-identical to the web call.
    public func resolve(_ feeling: DopeResolveInput) throws -> [String: DopeValue] {
        try resolveDopeParams(doc, feeling, consts: ["MAX_MOTES": MAX_MOTES], scatterKey: "moteSeed")
    }

    /// The whimsy-picked check glyph (composed on top of the numeric bag).
    public func pickCheckGlyph(whimsy: Double) -> CheckGlyph {
        pickBand(glyphBands, whimsy: whimsy)
    }
}

// MARK: - Metal drawable side (macOS/iOS only).

#if canImport(Metal)

// NOTE: `SolarbloomUniforms` + `packSolarbloomUniforms(...)` are now GENERATED by
// scripts/gen-uniforms.mjs into `SolarbloomUniforms.swift` (the SAME source that
// emits the MSL `struct SolarbloomUniforms`), so the Swift struct and the
// `.metal` struct cannot drift. The config below just supplies the standard
// half + the frame()/host-side extras and calls the generated packer.

/// Half-size of the checkmark glyph box as a fraction of min viewport dim.
private let CHECK_BOX_FRAC: Float = 0.16

/// The per-effect pass config. The genuinely code-shaped bits: the MSL function
/// names, the shadow height (= bloom radius), the per-frame (envelope + check
/// draw) hook, and the uniform packer that lays the resolved bag into the struct.
public struct SolarbloomConfig: PassConfig {
    public typealias Uniforms = SolarbloomUniforms
    public var vertexFunction = "solarbloom_vertex"
    public var fragmentFunction = "solarbloom_fragment"
    public var usesOrigin = true
    public init() {}

    public func shadowHeightFrac(_ params: [String: DopeValue]) -> Double {
        if case let .number(v)? = params["bloomRadius"] { return v }
        return 0.7
    }

    public func frame(_ info: FrameInfo, _ params: [String: DopeValue]) -> (amp: Double, extras: [String: Double]) {
        var overshoot = 1.0
        if case let .number(v)? = params["overshoot"] { overshoot = v }
        let amp = envelope(info.life, overshoot: overshoot)
        // The check draws on its OWN ~240ms clock (bespoke tempo), using the REAL
        // elapsed time — NOT the "animate on twos" stepped clock. The checkmark is
        // the functional "it worked" confirmation and must draw smoothly even at
        // high whimsy (where the bloom/motes intentionally step on twos).
        return (amp, ["check": checkProgress(info.elapsedMs)])
    }

    /// Pack the resolved bag → the struct via the GENERATED packer
    /// (`packSolarbloomUniforms`). The standard half + named scalars come from the
    /// generated code; here we only top up the host-side extras (the checkmark box
    /// + SDF stroke px) that depend on the live canvas, mirroring the web
    /// `passUniforms` hook, then hand the full extras map to the generated packer.
    public func packUniforms(standard s: StandardUniforms, params: [String: DopeValue], extras: [String: Double]) -> SolarbloomUniforms {
        // checkBox / sdfStrokePx depend on the live canvas; the host may override,
        // but we fill the analytic-fallback default so the shader still draws when
        // no SDF/glyph texture is bound. checkTexOn / sdfOn stay 0 until the host
        // uploads the baked-SDF / glyph texture and flips them on.
        var ex = extras
        let minDim = Float(min(s.resolution.x, s.resolution.y))
        let checkBox = CHECK_BOX_FRAC * minDim
        if ex["checkBox"] == nil { ex["checkBox"] = Double(checkBox) }
        if ex["sdfStrokePx"] == nil { ex["sdfStrokePx"] = Double(checkBox * 0.11) }
        return packSolarbloomUniforms(standard: s, params: params, extras: ex)
    }
}
#endif
